### ISSUE TITLE
Make `pending_transactions` work with Erigon

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v2-services#1054]
Code pointer: https://github.com/gnosis/oba-services/blob/73cbfa407827a1b5a2c5e81481f219c77cc9062a/solver/src/pending_transactions.rs#L35-L47

Currently the method uses `eth_getBlockByNumber(pending)` to get a list of pending txs in the mempool, which - last time I checked - wasn't supported by Erigon.

Instead they told us to use the https://geth.ethereum.org/docs/rpc/ns-txpool API (supported by geth/erigon).

This task captures implementing logic to find pending transaction with this API and flip flop between the two based on node availability.

**Comment by sunce86** [comment]
@fleupold 

`eth_getBlockByNumber(pending)` returns only subset of pending transactions from the mempool (only the transactions that are included in the pending block - block being currently mined). Based on the context of the `recover_gas_price_from_pending_transaction` i believe we need all the pending transactions from the mempool here?

**Comment by vkgnosis** [comment]
The context here is that we want to send out a new transaction from an account which should replace any potential existing transaction with the same (next) nonce. The only way we found to do that was to get all pendings transactions but we don't actually need all of them.

> only the transactions that are included in the pending block - block being currently mined

I think I brought this up before. This is what the documentation says but in practice it doesn't seem to be true for our nodes because they are not mining and there are more transactions returned than would go into one block. Or maybe we configure them in a special way so this happens. Still would be nice to not rely on this undocumented behavior.
