### ISSUE TITLE
Do we want one or multiple crates for shared functionality between orderbook and solver?

### ISSUE THREAD

**Issue by e00E** [gnosis/gp-v2-services#117]
We have the crates model, shared-arguments, tracing-setup but we could also have one crate that has those as modules like "services-core" in v1-services.
Having them as modules is a little easier to manage because there is only one dependency and creates less top level folders.
Having them as crates allows more fine grained reusability in case there is ever a third binary that only needs subset of functionality. But then we could still have features for individual modules or not care that we are importing more than we need.

**Comment by vkgnosis** [comment]
Another point here is converting u256 to and from bigint which is used by both binaries.

**Comment by vkgnosis** [comment]
I am tending towards have one bigger shared crate because we would end up with too many very small crates otherwise. As of right now it would absorb shared-arguments and tracing-setup as modules. The model crate I would still keep separate as I could imagine another project wanting to eventually use it.
