### ISSUE TITLE
API Price Estimates Can Lead To Untradable Orders

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#1253]
It is my understanding, that adding ParaSwap price estimator to the API increases the amount of tokens the API supports by taking advantage of more liquidity.

The issue, however, is that the the solution objective value is computed using baseline price estimates, therefore (at least to my understanding), it would ignore solutions that trade tokens for which the baseline price estimator cannot find a path.

This might cause some UX issues where a user is able to create an order, but we can never execute the trade because there is no price estimate for the objective value computation.

**Comment by fleupold** [comment]
I think the constraints in the driver are still a little bit less strict as for the API. E.g. I noticed stkAave is still tradable (even if it wasn't until we enabled it by using Paraswap in the API). The reason seems to be that in order to price a token we only take the current spot price (regardless of pool size), whereas in the API we want to be able to trade at least 1ETH worth (which e.g. on the stkAave uni v2 pool is not possible despite it existing).
