### ISSUE TITLE
Do not settle uneconomical solutions / negative objective value

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#1320]
I'm not sure if this has been captured somewhere else already so these are some thoughts I had to today when dealing with our current overpayment situation. 

To prevent overspending we should enforce that we will not settle solutions which are uneconomical. This is partly encoded by the current objective value function which is `surplus + solver_fees - cost`. Here `surplus` is roughly how happy a user is with their trade because the price was better than what their limit was.
For economic viability the surplus is not important, only fees earned and cost in gas paid so we should filter out solutions where this part is negative. From the remaining solutions we can take the maximum of the objective value.
The economic viability takes the subsidy into account as we already pretend orders earn their unsubsidized fee for this calculation.

The problem with this approach is that it easy for orders to become nonviable if on chain conditions worsen slightly  like when the gas price or gas use increases. Currently we give users the most optimistic fee possible so any worsening condition could make the the order nonviable. To fix this we could introduce something like a "max extra subsidy due to changing conditions" constant that is checked in the solver. Or we could make users sign a fee that is a little higher than our target fee factor to have some lee way. On the other hand then we would want a way to take less fees than what the user signed in case conditions do not get worse.
It is problematic that we commit to this best case estimate because the settlement will happen some time later. If on chain conditions get worse we absorb the cost.

**Comment by vkgnosis** [comment]
This is also important to promote merging of solutions. Currently we have cases where a merged settlement has lower objective value than the individual mergees because some of them are negative. This causes us to for example do two single trade settlements because next run loop we do not filter out the negative settlement causing us to waste gas on separate transactions.
To fix this for single order solvers we have to make the merging algorithm smarter. Maybe we have to simulate the individual solutions first and then merge in a way that only increases objective value. Here we would subtract some gp gas overhead from the individual settlements to figure out how they would change the objective value as part of a bigger settlement. Then simulate the merged settlement.


> I agree with this proposal. Do you think we should first make the subsidy a fixed $ amount or should we limit our overspending even in the current % discount model?

I don't know. Not sure if it matters for this issue. Either way we have to address this quickly.

**Comment by vkgnosis** [comment]
We have to decide how the surplus should factor into this. Is it allowed to make up for an uneconomical solution? The way the objective value is currently calculated the answer is yes. If the surplus is very large we are also ok with losing money on executing the trade. I don't think this should be the case. Instead we could do

```rust
if solver_fees > cost {
    surplus + solver_fees - cost
} else {
    -1
}
```
with the assumption that negative objective value solutions do not get settled. The point being that an uneconomical solution can never get picked. I'm not sure a calculation like this is doable for the optimizers. What do you think @marcovc?

If this isn't possible then we might want to add a factor to the surplus so it counts less than the fees and gas cost. I'm not sure from the top of my head in what unit surplus is given but using `0.1 * surplus` could mean something like the value of the surplus in the native token must be 10 times as much the extra gas cost.

**Comment by marcovc** [comment]
I never really liked our objective function (adding user surplus with our profits seems odd to me). There are usually 2 solutions to these situations: weighted average (as your last suggestion above), or a Pareto frontier, for example saying that a solution is better than another if it delivers more surplus to users, breaking ties with the one that gives us more profits. Unfortunately this last option is not great when we are comparing real-valued numbers (a common solution to this is to do some sort of "discretization"). Both of these can be done in the solvers, the latter one likely having a performance penalty. 

You first suggestion is easy: we just add a constraint that we must be profitable (solver_fees >= cost). This means if the solver can't find a solution where we aren't profitable, it will send back the trivial solution. Adding this constraint makes a lot of sense to me.

My concerns about this is that currently quasimodo enforces a more relaxed version (surplus+solver_fees - cost>=0)  and even so it replies with a trivial solution for 3/4 of the instances. If we enforce this stronger constraint, I suppose it would seldom find any solution...

**Comment by fleupold** [comment]
> and even so it replies with a trivial solution for 3/4 of the instances.

Does this number include cases in which the limit price is violated, or are you saying that 75% of all solutions that respect the limit price are throw away because they are not economically viable. If not, can we get the latter number?

> I never really liked our objective function (adding user surplus with our profits seems odd to me)

One thing that is nice about the current model is that at least in the single order case it's exactly what dex aggregators already use to come up with a best solution (just that fee=0 and cost is paid by the user for execution), so it works out of the box with our single order solvers.

What we want to avoid is a solver creating a very complicated settlement (costing $100 more) in order to get $1 more surplus and win the competition. But maybe if the solver only receives whatever they collected in fees + a fixed CoW token bonus it's up to them how much they value the fees (if a solver is happy to make a loss for some CoW token reward, they are invited to do so).

The other alternative would be to capture some of the surplus and not pass it on to the user in case their fee is not sufficient. Would Quasimodo theoretically be capable of internalising surplus (keeping it rather than paying it out to the user) in order to make up for when `cost > fees`? My intuition tells me this would be a non-linear constraint.

**Comment by marcovc** [comment]
> Does this number include cases in which the limit price is violated
Yes.

> or are you saying that 75% of all solutions that respect the limit price are throw away because they are not economically viable. If not, can we get the latter number?

I can yes. I'll re-run these benchmarks sometime this week and post the numbers.

> What we want to avoid is a solver creating a very complicated settlement (costing $100 more) in order to get $1 more surplus and win the competition.

Yes, that is why I mentioned that it requires some form of "discretization".

> But maybe if the solver only receives whatever they collected in fees + a fixed CoW token bonus it's up to them how much they value the fees (if a solver is happy to make a loss for some CoW token reward, they are invited to do so).

Not sure I understand, I guess you're in a setting where the solvers, and not the driver, are also responsible for settling the transaction on the blockchain? Otherwise what could be the solver losses?

> Would Quasimodo theoretically be capable of internalising surplus (keeping it rather than paying it out to the user) in order to make up for when cost > fees?

I guess we could do something like
```
maximize user_surplus + fees - costs
subject to:
internalized_surplus + user_surplus = surplus
internalized_surplus + fees - costs >= 0
```
?

**Comment by marcovc** [comment]
> I can yes. I'll re-run these benchmarks sometime this week and post the numbers.

https://gnosisinc.slack.com/archives/CS6NV17HP/p1636107631024300
