### ISSUE TITLE
Accept transaction as completed when first node responds

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v2-services#1374]
E.g. https://logs.gnosis.io/goto/f7ce5c6af3c03c6db1362cfa4e1b9b6d

Here we knew at 15:17:19.418 that the transaction was not going to get through. We then waited for 4 minutes (20 blocks) on our faster node before realising:

> failure: transaction confirmation timed-out

And then another 30s before our slowest node accepted this sad fact as well.

Overall we lost 5 minutes:

![image](https://user-images.githubusercontent.com/1200333/140961971-0d6f52b4-b56a-4cbb-8639-6421e3dc6826.png)

Maybe we can inspect the errors from each individual machine and unless it's an intermittent connection issue accept that the slowest node will also eventually realise the failure.

**Comment by nlordell** [comment]
In the first example, I see a `replacement transaction underpriced` error. In theory this shouldn't happen because we ensure that we increase the gas is high enough before submitting right?

In the second case is interesting because there was a 3 minute difference between one of the nodes we are connected to seeing the block including the failed transaction and the retry loop finishing. Is it really taking 3 minutes to propagate blocks?

**Comment by fleupold** [comment]
I think this was after a restart so possibly we didn't find the old tx and therefore didn't choose a high enough replacement gas price. 

It then took 3 minutes (on our faster node) to mine through our confirmation timeout of 25 blocks.

**Comment by sunce86** [comment]
I believe this issue is not relevant anymore after the settlement submission refactor.
