### ISSUE TITLE
Filter for settled orders

### ISSUE THREAD

**Issue by josojo** [gnosis/gp-v2-services#140]
The orderbook service should not propagate already settled orders.

Hence, it should listen to the Trade contract events and stored all settled UID. Initially, this storage should happen in memory, but later the data will be put into a DB.

Each maintenance run, the orderbook service should listen for new Trade events between the last documented block and the current one and update the list of settled orders. And of course, remove the settled orders from the orderbook.

**Comment by e00E** [comment]
It's more complicated because of reorgs. We might need something like the event based orderbook from v1, but at least here we only have fill amounts.

**Comment by josojo** [comment]
Yeah, agree that eventually, we need a more complex solution. 

We could do the following:
Create a hashmap of `historic_orders` and `active_orders`. If a new Trade events is streamed, we will swap the order from `active_orders` into `historic_orders`. and if the event is reverted, then we will do the opposite. One could say that his should happpend later with proper DB-solutions. But I think it is fine if we are doing it even now with in memory hashmaps.

I can strive for it, but I am not sure whether we should have something simpler for the demo...

**Comment by fleupold** [comment]
Instead of deleting orders from the DB, we could also give them an "invalidated" timestamp. This would allow us to easily do time travels on the data and simulate the orderbook at a given timestamp. A block reversion would just remove the invalidated timestamps of the trades it settled.

Maybe this could also be reflected in the ordebook datamodel (e.g. on metadata) and then we just add this extra check to the filter call when we fetch all orders from the list.
