### ISSUE TITLE
Settlement submission refactor

### ISSUE THREAD

**Issue by sunce86** [gnosis/gp-v2-services#1407]
Currently, we have several transaction submitting strategies, each with a different submission logic and parameters:
1. CustomNodes
2. Archer
3. Flashbots

General submission logic needs to be extracted in order to avoid code duplication and make maintenance easier.
Idea is to share common submission logic, but to have different implementation for submit/cancel functionalities. Also, smaller differences in algorithm should be handled through single parameter object containing all differences.

Refactoring will be done in steps:

- [x] Extract `Submitter` (common submission logic) from Archer and Flashbots and eliminate both.
- [x] Refactor CustomNodes to use `Submitter`
- [x] Refactor `Submitter` to support submitting settlement to multiple destinations at the same time.
- [x] Build a wrapper around `Submitter` that will implement smart decision making on type of the strategy/strategies to use for each individual settlement.

After the refactor, adding a new strategy will be equal to implementing submit/cancel functionality of newly added strategy.

**Comment by fleupold** [comment]
Looks good. One thing I'd like to think about is how gas estimates work with the different strategies. Can we extract that logic in the existing GasEstimating abstraction or will different strategies (e.g Archer vs CustomNodes) need fundamentally different gas estimates.

> Refactor GeneralSubmission to support submitting settlement to multiple destinations at the same time.

Maybe it could just take different sub strategies at the same time? This way we could use Flashbots and Archer at the same time (which I believe is something we'd like to do).

> After the refactor, adding a new strategy will be equal to implementing submit/cancel functionality of newly added strategy.

Sounds good! Even for the CustomNodes we want cancellation of submission in case simulation fails, right (by resubmitting a same tx nonce with higher tip)?

**Comment by nlordell** [comment]
Instead of introducing a new submission type (`GeneralSubmission`), maybe we can just reuse the existing `SolutionSubmitter`.

> One thing I'd like to think about is how gas estimates work with the different strategies

When creating the strategy, we could just:
```rust
let gas_estimator = PriorityGasEstimator::new(vec![
   StrategySpecificGasEstimator::new(),
   passed_in_gas_estimator,
]);
```

> Maybe it could just take different sub strategies at the same time?

The way I imagined it, we would have some general submission logic (i.e. the current submission loop that we use in `Archer` and `Flashbot` submission) and then pass in a `Submitting` trait that could combine/duplicate as needed:
```rust
struct SplitSubmitter {
   inner: Vec<Box<dyn Submitting>>,
}

impl Submitting for SplitSubmitter {
  async fn send() {
     try_join!(self.inner.iter().map(|submitter| submitter.send()));
  }
}
```

Or choose a submitter based on value:
```rust
struct ValueBasedSubmitter {
   small: Box<dyn Submitting>,
   large: Box<dyn Submitting>,
}

impl Submitting for SplitSubmitter {
  async fn send() {
     let submitter = if total_eth_value() > ether(5.0) {
         &self.large
     } else {
         &self.small
     };
     submitter.send().await
  }
}
```

> (by resubmitting a same tx nonce with higher tip)?

:+1: Could save us some gas.

**Comment by vkgnosis** [comment]
We talked about this on Slack too but to reiterate:
CustomNodes should be changed to not use the gp-transaction-retry crate and ethcontract anymore because that doesn't give us enough control. Like for Archer and Flashbots we will want to manually submit to the node and manually check whether the tx got mined. This will make it's code align more with the other strategies.

**Comment by sunce86** [comment]
Finished.
