### ISSUE TITLE
Specialized Settlement Submission Strategies

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#1538]
With the current work going into refactoring the settlement submission strategies, it would be great to add some specialized logic to our strategies to:
- For settlements without any trade interactions (WETH unwraps are OK to include) don't send the settlement to a private network
- For settlements only including small orders (so not enough to be attractive to MEV) over very deep pools (USDT-WETH for example - where the chance of price movement beyond the slippage is very very low) do not submit to a private network

**Comment by sunce86** [comment]
Related to task 4 from https://github.com/gnosis/gp-v2-services/issues/1407

I would argue (for both) that we should substitute `do not submit to private network` with `submit to both private networks and public mempool`, because Flashbots give us also the protection against failing transaction that both of these situations would benefit from.
