### ISSUE TITLE
Allow Pre-Sign Orders to be Created Without Allowance and/or Balance

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#1545]
Balance and allowance checks were used as a form of DoS attack prevention. Since we aren't protected for pre-sign orders anyway, we can remove this restriction for them enabling Yearn to use CowSwap for harvesting swaps.

**Comment by fleupold** [comment]
Here is their use case: https://github.com/yearn/hardhat-monorepo/blob/main/packages/yswaps/scripts/multicall/ThreePoolCrvMulticall.ts

The goal is to replace the 0x hop with CowSwap.

If we wanted to we could keep the allowance check. For them the issue is the balance check, as they would like to place the CowSwap order (USDC -> yvBoost) before the swap tx is signed (multi-signature transaction takes a couple of hours) and before the first leg (CRV -> USDC), which they do using manual unwrap logic, is done (therefore USDC balance is 0 at the time of order placement).

Another - spam safe - approach would be to revisit the approach where we emit all relevant data in an event in the same tx as the PreSign takes place (this way the API can index it without requiring a call).

**Comment by nlordell** [comment]
> Another - spam safe - approach would be to revisit the approach where we emit all relevant data in an event in the same tx as the PreSign takes place (this way the API can index it without requiring a call).

How do we deal with orders that don't specify a high enough fee or trade tokens that aren't supported in those cases? I think we could just ignore those orders, but then it becomes a very expensive "order proposal".

**Comment by nlordell** [comment]
Yes, for this kind of order, having the solvers take fees out of the order surplus would be ideal.

**Comment by nlordell** [comment]
> If we wanted to we could keep the allowance check.

I think it might also be good to drop the allowance check. It would allow, for example, a Safe to bundle allowance and pre-sign into a single transaction.
