### ISSUE TITLE
Record Settlement Gas Cost vs Order Fees Collected

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#1573]
We currently record in the `orderbook` database rich `fee_amount` data with each order (so AFAIU, enough to recover the estimated amount of gas for an order in ETH).

This issue captures the work to recover additional settlement fee information (so gas used and effective gas price) as well so we can gather better data on how far off our fee estimates are vs. what they actually cost.

**Comment by nlordell** [comment]
Note that this data can be read from the block-chain "after the fact". This means that, while we haven't been recording this, we can still retroactively compute cost coverage for our orders.

Maybe this data recording is something that can be delegated to a background worker of some sort.

**Comment by vkgnosis** [comment]
We have logging in the solver now for easy manual analysis. I am going to write a program that uses the database to automatically find settlements an their orders and gets the transaction gas data from an ethereum node. If that works well I like that approach because it is decoupled from the rest of the system.

**Comment by nlordell** [comment]
Is this something that we should add to our database or should it be completely separate process?

**Comment by vkgnosis** [comment]
I'm not sure if we need it in the database or if it would be fine to run the tool from time to time to generative a csv file or something like that. If we do want it in the database I'm not sure. Separate process feels nice because it *can* be a separate process as it doesn't need to be synchronized to the main process in any way (?). Currently I feel I should prototype it as a standalone application.

**Comment by vkgnosis** [comment]
Created https://github.com/gnosis/gp-v2-fee-analysis . Currently prints information to stdout for settlements in the last 100 blocks.

**Comment by vkgnosis** [comment]
Next step: More comprehensive analysis using this tool. (Not necessarily by me.) Should be easy to adapt it for specific use case.
