### ISSUE TITLE
Separate order fetching and solver friendly order serialization into separate components

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v2-services#194]
This task is a more long term thought on how to make the system scalable and allow easy addition of other onchain liquidity sources.

#176 introduced the HTTP based solver and fetches Uniswap orders directly in the solver code. I understand this was done for pragmatic reason. In the longer term I think the fetching of onchain liquidity sources should happen independent of the specific solver used to allow it to not necessarily touch any solver code.

E.g. we might want to add SushiSwap and Balancer pools sooner rather than later. The former would still be compatible with the slightly less naive solver whereas the latter would not. I think it would be nice to have an orthogonal "onchain liquidity fetching" chain that returns a list of abstract Order types. Different solvers can decide to handle or not handle specific order types (each order could provide a way of how it can be approximated with the most basic ordertype that all solvers support - limit or linear orders).

When adding a new liquidity source, we only need to add a new "fetcher" to the chain and provide a way how it can be approximated by limit orders. Additionally we can later add custom handling for more customized order types in each solver individually. This separates concerns of order fetching and solver friendly order serialization.

**Comment by vkgnosis** [comment]
After seeing PR I understand this more. Commenting here instead of the PR for more high level stuff.

I agree with separating liquidity source fetching from the solver code is good. This gives the driver more control over how this is done and makes the data more easily sharable between solvers and also disentangles the solver from networking related code as it can work with the liquidity sources as data.

I am doubtful that we can represent liquidity sources to the solvers as limit orders without letting the solver know the exact details of the liquidity. Yes, everything that mechanically works like uniswap can be represented by the same data and we can do some things with traits there to reuse code (likewise for different RFQ systems) but I feel that is as far as we can go:

All liquidity have in common that they should only be used if they are useful for user orders. A liquidity source does not have tokens but it can be used to convert tokens from users. If liquidity sources were not distinguishable from user orders then solvers would not be able to work properly. For example it could try to match the order representing wrapping ETH with the order representing unwrapping ETH. Or it would use the wrapping order directly without giving it a user order as input.

A uniswap pool isn't equivalent to a limit order because it has dependencies between price and the pool size and maximum tradable amounts.

**Comment by fleupold** [comment]
I see your point about some forms of liquidity providing no value to the system unless matched with user orders (e.g. wrap/unwrap ether). For this it might be possible to pass a flag "creates_value" or something the like to the solver (similarly of how uniswap orders have a "is_mandatory" flag) or define some minimum "utility" threshold for something to be included.

My goal with the liquidity enum was to model the different types of orders the solver understands. As of today this is limit orders and uniswaps. In the future for the http_solver it might be groups of limit orders (where n out of m have to be filled - this can model "basket orders"), linear orders or split/merge orders.
My goal was not to shoehorn uniswap pools as limit orders (in the example I mentioned I was thinking of a separate "simple" solver that only understands the concept of limit orders and thus needs to work with approximations, a concept which the solver team has explored [here](https://gnosisinc.slack.com/archives/C8YGC05NG/p1605777199005800)). However, I believe that if we had multiple fundamentally different solver types, each of them should likely have their own liquidity enum (in this case each liquidity source might have multiple ways of how it represents itself to each individual solver).

Do you have a concrete suggestion what you would change in the proposed architecture? One thing that is bothering me a little bit is the interlacing of plain old data (buy, sell token etc.) and the settlement handler object. I could break it up in two separate objects (one data, one handler) but I'm not sure this is changing much.

**Comment by fleupold** [comment]
Tagging @josojo @nlordell for input as well. Let's do a more high level design discussion here rather than on the individual PRs.

**Comment by nlordell** [comment]
> My goal with the liquidity enum was to model the different types of orders the solver understands.

I really like this approach, the `Liquidity` enum can be extended to include other kinds of liquidity sources:
- CMMs (if we implement those as interactions)
- Other AMMs (Balancer, Curve)
- 0x orders (which we will probably need add very soon)

> For this it might be possible to pass a flag "creates_value" or something the like to the solver

The solver input can just be split into GPv2 orders which have priority, and the `Liquidity` sources (which can be used to provide liquidity to settle otherwise impossible batches - like reaching into a Uniswap pool to trade a token in surplus). In this regard I do agree with @vkgnosis that conceptually orders and liquidity sources are a little different and probably need to be treated differently by the solver. Something like this is what I'm suggesting:
```js
{
  orders: [
    { ... },
  ],
  liquiditySources: [
    { kind: "uniswap", reserves: [ "10000000", "200000000" ] },
    { kind: "0x", makerAmount: "200000000", takerAmount: "4000000000" },
  ],
}
```

> I agree with separating liquidity source fetching from the solver code is good. This gives the driver more control over how this is done and makes the data more easily sharable between solvers and also disentangles the solver from networking related code as it can work with the liquidity sources as data.

:+1: I think this is quite important. I was under the impression that the driver would pass the Uniswap reserves as solver input.

**Comment by nlordell** [comment]
Regarding @josojo 's comment :
> Since we don't wanna pull and store the information of one liquidity source several times for each solver, I would introduce another trait: representLiquidityForSolver, that would transform one Liquidity object of the Liquidity-Enum and destruct it into a good representation for the solver. For each liquidity, we can have several representLiquidityForSolver traits implemented.

I think this fits nicely with the `Liquidity` enum:
```rust
enum Liquidity {
    Linear(/* linear parameters */),
    Swap(/* reserves */),
    // ... other kinds
}
```

Then each `LiquiditySource` implementation would return the same `Liquidity::` variant. For example:
```rust
impl LiquiditySource for UniswapLiquiditySource {
    async fn get_liquidity() -> Result<Liquidity> {
         //...
         Ok(Liquidity::Swap(/*... */))
    }
}

impl LiquiditySource for SushiSwapLiquiditySource {
    async fn get_liquidity() -> Result<Liquidity> {
         //...
         Ok(Liquidity::Swap(/*... */))
    }
}
```

That is, the concrete `Liquidity` type represents all know liquidity sources that the solver understands.

**Comment by vkgnosis** [comment]
>  I think this is quite important. I was under the impression that the driver would pass the Uniswap reserves as solver input.

I was unclear with the wording here. There is the python solver and there is a Solver trait in the solver rust crate. The python solver just takes data as input without other IO. At the moment the implementation of the solver trait for the python solver internally fetches the uniswap pools and so does the naive solver. What I think is part of this issue is to have this happen even outside the Solver trait so that the solver trait gets all of the liquidity sources as it's input and then decides how to pass them to the specific solver backend.

**Comment by nlordell** [comment]
> What I think is part of this issue is to have this happen even outside the Solver trait so that the solver trait gets all of the liquidity sources as it's input and then decides how to pass them to the specific solver backend.

Ahh OK.

Personally, I also prefer for the liquidity fetching to happen outside the solver backends and be passed in as input. That being said I do agree that they need to be differentiated from regular orders.

**Comment by josojo** [comment]
@nlordell But how do you solve the issue, if you want to represent the same liquidity source with different models?
Yes, your example works nicely:
```
impl LiquiditySource for UniswapLiquiditySource {
    async fn get_liquidity() -> Result<Liquidity> {
         //...
         Ok(Liquidity::Swap(/*... */))
    }
}

impl LiquiditySource for SushiSwapLiquiditySource {
    async fn get_liquidity() -> Result<Liquidity> {
         //...
         Ok(Liquidity::Swap(/*... */))
    }
}
```

but what about:
``````
impl LiquiditySource for CurveAsLinearOrders {
    async fn get_liquidity() -> Result<Liquidity> {
         //...
         Ok(Liquidity::Linear(/*... */))
    }
}

impl LiquiditySource for CurveAsAMM {
    async fn get_liquidity() -> Result<Liquidity> {
         //...
         Ok(Liquidity::Swap(/*... */))
    }
}
```
I was trying to avoid two calling twice the Ethereum node for the same object( curve AMMs).

If we are going with Felix's approach, and want to avoid double Ethereum nodes, then we would have a mapping between Liquidity Enum element - e.g. Linear(curve), AMM(curve) - and on-chain liquidity - e.g. curve. 

In order to not maintain this mapping, I think it is wise if Liquidity Enum only contains 1 on-chain liquidity. And different representations for solvers are compiled on the flow.

But as mentioned, I think this can be build in later. I really like Felix's first suggestion.

**Comment by josojo** [comment]
> I see your point about some forms of liquidity providing no value to the system unless matched with user orders (e.g. wrap/unwrap ether). For this it might be possible to pass a flag "creates_value" or something the like to the solver (similarly of how uniswap orders have a "is_mandatory" flag) or define some minimum "utility" threshold for something to be included.

I agree. The information on whether liquidity provides value needs to be in the system. But we use a flag or just manage these liquidities differently: e.g. in two 
```rust
let liquidity_requests: Vecs<Liquidity> <-- retail orders
let usable_liquidity: Vecs<Liquidity><-- Curve, Uniswap
```

**Comment by fleupold** [comment]
> [...] the Liquidity enum can be extended to include other kinds of liquidity sources:
> - ...
> - 0x orders (which we will probably need add very soon)

Here my thinking was that 0x orders are actually just limit orders as far as the solver is concerned. They would come from a separate liquidity source (e.g. the ScpLiquiditySource) but don't have to be modelled differently for the solver. They need to be translated into interactions differently than EOA orders but this logic can stay in the liquidity source and connected via the [SettlementHandling](https://github.com/gnosis/gp-v2-services/blob/fe5e3ab3dc06035af294b42fef1afccc9f16d9ef/solver/src/liquidity.rs#L47) object.

Another example for onchain orders that should potentially be handled just like EOA orders could be if we implemented Gnosis Safe orders the way [Martin suggested](https://gnosisinc.slack.com/archives/CC3C5SMB5/p1610542399447900). This is why I'm not sure we need to split EOA limit orders and other form of on-chain limit orders in the datatype.

**Comment by nlordell** [comment]
> But what b

@josojo, that is a fair point. We can change the trait to return more than one liquidity object:
```rust
impl LiquiditySource for CurveLiquidity {
    async fn get_liquidity() -> Result<Vec<Liquidity>> {
         //...
         Ok(vec![
             Liquidity::Linear(/*... */),
             Liquidity::Swap(/*... */),
         ])
    }
}
```

**Comment by nlordell** [comment]
> Here my thinking was that 0x orders are actually just limit orders as far as the solver is concerned.

One minor technicality is that they operate differently at a SC level, they take then give tokens instead of giving and then taking tokens. In that regard, they require their input amount to be fully covered by EOA order output amounts. (In general, the sum of EOA order outputs - i.e. sell amounts - needs to be greater than, or equal too the some of liquidity inputs - "buy amounts" - or else the SC will revert).

Another aspect, is that 0x orders shouldn't ever trade with other liquidity sources. In practice I don't think that it will happen, but maybe, once in a blue moon it might (if some AMMs have really bad prices for long-tail tokens, and a ring could enable a trade with another AMM).

**Comment by fleupold** [comment]
The challenge of settlement ordering is a good point. One potential workaround we have discussed in the past was to wrap the entire settlement in a flash loan to avoid temporarily negative balances, but I don't think this idea is speced out enough to rely on it in our design (e.g. flash-loans can be expensive, might not support all tokens, etc).

I wonder if the scenario you described could happen even if user orders were a separate entity. Imagine there is some arbitrage opportunity on-chain (yielding a net benefit of 1 GNO) but it requires a certain amount of input capital to execute that we don't fulfil (e.g. 1YFI). Do we model these capital requirements in the solver or do we today just verify token conservation at the end of the settlement (will post this question in the solver channel)?

Not super related to this discussion, but generally I wonder which component should be in charge of ordering interactions (e.g. if an OWL->GNO order is matched via the ETH uniswap route, we need to first swap OWL for ETH and then ETH for GNO - finding a valid sequence might not always be trivial)

Back to the topic: I think the technicality you describe could be either solved by another variant in the enum or a field on the limit order specifying something like post funded or pre funded. Going beyond the previous example I'd then argue that a 0x order and another on-chain limit order liquidity source (e.g. Oasis DEX) are not fundamentally different types to the solver.

**Comment by vkgnosis** [comment]
> Not super related to this discussion, but generally I wonder which component should be in charge of ordering interactions 

I always thought this would be the python solver because this ordering is inherently part of the settlement. Otherwise we end up implementing a solver for the output of the solver.

--- 

The way I am thinking about this is issue at the moment is:

On one side we have the low level state of the world which includes things like orders from the order book, uniswap pools, sushiswap pools, limit orders on other exchanges, the knowledge that eth and weth can be converted  between, ...

On the other side we have information that a solver understands. What that is depends on the solver. At the moment the python solver understansd orders from the order book and uniswap pools.

The question is what the best way to connect these is.
Abstracting over exchanges that are all functionally uniswap-like just with different is always good because for a solver there is no reason to differentiate between them. So we could definitely start out with a PR that just does this abstraction.
Likewise "true" limit orders from other on chain sources that are functionally the same can be abstracted over.
At this point of the discussion whether we have a bool "isOrderBookOrder" and aggregate order book limit orders with other on chain limit orders, or whether we have two separate types OrderBookOrder and OtherOnChainLimitOrder is not relevant. Either way the solver can differentiate them which is the important part.

Then there are more complex abstractions like encoding the knowledge that eth and weth are equivalent as a limit order. This might allow a solver to consume this information even when it is not natively capable of handling the "raw" information. However, another solver might be able to work with this directly and even run more efficiently. It depends on the solver. For this reason I do not want to force any lossy abstraction on the solvers.
Likewise a 0x source can in some way be encoded as a limit order but then it has the additional requirement that it shouldn't trade with other liquidity too (because 0x might internally use them?). So again for some solvers converting to limit order is helpful but for others it might be harmful.

Maybe a good architecture would be to start out with all the lossless abstractions (like different uniswap forks) and then have optional machinery to further transform the information. In the rust Solver trait we pass the lossless information and then specific Solver implementations can use the machinery to adapt to their specific solver.
I feel this is very flexible and allows us to extend the model when needed without having to make difficult design decisions over the correct liquidity abstractions now when we don't even know if the solver will ever be able to handle them.

**Comment by vkgnosis** [comment]
With pseudo code examples (forgive bad naming):

```rust
pub trait Solver {
    async fn solve(&self, world: World) -> Settlement;
}

struct World {
    order_book,
    uniswap_pools,
    sushi_pools,
    wrappable_tokens,
    on_chain_limit_order_exchange_no1,
}

type OrderBook = Vec<Order>;
type UniswapPools = HashMap<TokenPair, Pool>;
...

fn combine_uniswap_likes(uniswap, sushi) -> Vec<GenericUniswapPool>

fn convert_wrappable_tokens_to_orders(wrappable_tokens) -> Vec<Order>

impl Solver for PythonSolver {
    async fn solve(&self, world: World) -> Settlement {
        let pools = combine_uniswap_likes(world.uniswap, world.sushi);
        let mut orders = world.order_book;
        orders.extend(convert_wrappable_tokens_to_orders(world.wrappable_tokens));
        ...
    }
}
```

**Comment by nlordell** [comment]
@vkgnosis This is similar to how I envisioned it as well, but I do like the `LiquididtySource` and `Liquidity` abstraction. Additionally, I think it makes sense for the `World` to produce some standardized data that is passed to all backends instead of each backend building their data from `World`. The `NaiveSolver` can simply ignore non-Uniswap pools for example.

```rust
pub trait Solver {
    async fn solve(&self, batch: Batch) -> Settlement;
}

pub struct Batch {
    orders: Vec<Order>,
    liquidity: Vec<Liquidity>,
    // OR
    liquidity: Vec<Liquidity>, // orders are Liquidity::Order(order)
}

struct World {
    order_book,
    liquidity_sources: Vec<dyn LiquiditySource>,
    wrappable_tokens,
    on_chain_limit_order_exchange_no1,
}

impl World {
    pub fn create_batch(&self) -> Result<Batch> {
        Ok(Batch {
            orders: [self.order_book.get_orders(), convert_wrappable_tokens_to_orders(world.wrappable_tokens)].concat(),
            liquidity: self.liquidity_sources.flat_map(|source| source.get_liquidity()).collect(),
        })
    }
    
    pub fn encode_settlement(&self, settlement: Settlement) -> Result<EncodedSettlement> {
        encode_executed_order(settlement.executed_orders);
        encode_liquidity_interactions(settlement.used_liquididty);
        // ...
    }
}
```

**Comment by fleupold** [comment]
The benefit an abstract enum, that is close to the solver's internal representation, brings imo is that when adding a new liquidity source, we only have to know how to create this abstract solver supported liquidity type from our on-chain protocol.
With the `World` suggestion I'd define a new type add it as a field to world and then had to decide in all the callsites (most notably the solver encoding/settlement handling) how to deal with it. In the original proposal the code for adding a new source can be very localized and doesn't require any internal knowledge of the solver(s). This I imagine would make it easier for (potentially external) developers to add their protocol as a liquidity source.

Of course this is only of benefit if many "sources" can translate to the same solver representation (|solver order types| << |onchain liquidity sources|) which is my assumption. If we had to create a special case in the solver for each on chain liquidity source there wouldn't be much benefit in abstracting over different sources.

Regarding @josojo's concern about having fundamentally different solvers (e.g. one that can only operate on linear approximations of functions), whose order types don't really overlap (are not a strict sub/superset), we could have a separate Liquidity type for each solver and "visit" each liquidity source with the solver object that is currently being used. Then each liquidity source would have to potentially have different code for translating itself into solver specific liquidity.


```rust

enum Solver {
  SolverA(...),
  SolverB(...),
}

enum SolverALiquidity {
  LimitOrder(...),
  AmmOrder(...),
  ...
}

struct SolverBLiquidity(LinearOrder)

impl LiquiditySource for Uniswap {
    async fn get_liquidity(&self, solver: Solver) -> () {
         match solver {
            SolverA => Ok(SolverALiquidity::AmmOrder(...)),
            SolverB => Ok(SolverBLiquidity(LinearOrder::new(...))),
    }
}
```

But I'd not start this refactoring before it becomes necessary.

**Comment by vkgnosis** [comment]
It looks like one big design decision is whether we are planning on writing this code for our specific python solver or trying to keep it generic for potential other solvers. I don't mind being specialized for that solver only but we should in that case clearly state and follow that goal and not smuggle in other abstractions (not saying we do, just a worry for the future).

Although still feel that there is little extra work with World while having the benefit of a more general design.
If the assumption is that we only have the python solver then with World we could have a function transform_world_for_python_solver and adding a new source involves adding a field to World and touching this function which does not seem very different from the specialized approach.
If the assumption is that there are many solvers then it is true that adding a new source is more work but it is also true that the specialized approach would not work at all so the comparison is not fair.

**Comment by fleupold** [comment]
If I understand correctly, the designs are actually quite similar (we might already have consensus just call things slightly differently).

"World" contains all possible on-chain components (what I maybe called "LiquidityFetcher" in the description of #225 - it is not yet implemented to keep the change smaller). 
Each component of the world knows how to translate itself to a list of a potentially solver specific liquidity (at the moment we only support the python solver). "World" itself can expose an overarching `get_world_for_python_solver` and would return a list of python_solver compatible liquidity like @nlordell suggested in his pseudo code (called `create_batch`). Is this functionally equivalent to `transform_world_for_python_solver` that you suggested @vkgnosis?

Specific remaining differences are:
- in my PR I don't differentiate between off-chain limit orders and on-chain limit orders (I will add a boolean flag, which we said is equivalent to a separate subtype)
- The naming of the enum might make it sound more abstract than we eventually want it to be (we could already call it HttpSolverLiquidity or PythonSolverLiquidity) although I personally prefer the more general name until we have two different types to differentiate (but no strong feelings).

Am I missing any other differences?

One aspect we haven't yet discussed is the conversion of a solver identified match into trades and interactions. In my proposal we attach a settlement handler on each liquidity instance, however we could also have one single settlement handler attached with each abstract type of liquidity. The reason for my suggestion was that if two sources (e.g. Uniswap. SushiSwap) map to the same liquidity object type, they might still require very different handling. Maybe this is a no-brainer but just wondering if there are other ideas.

**Comment by vkgnosis** [comment]
> Is this functionally equivalent to `transform_world_for_python_solver`

Yes I think so.

---

I suspect it would be easier to work with the solver specific liquidity if it wasn't in the vec-of-enum form but as struct-of-vec

```rust
struct SolverWorld {
    limit_orders: Vec<LimitOrder>,
    uniswap_like_amms: Vec<AmmOrder>,
    ...
}

--- 

I don't think we need

```rust
pub trait LiquiditySource {
    fn get_liquidity(liquidity_so_far);
}
```

This doesn't have to be generic like this which will limit the interface yes. Instead if we have a World, then we can call each specific liquidity source without going through a trait. This allows to have different parameters for different sources. Then for example OffChainOrderBook will not have a parameter liquidity_so_far.

**Comment by vkgnosis** [comment]
> One aspect we haven't yet discussed is the conversion of a solver identified match into trades and interactions.

I am not sure. It feels like there should be a better abstraction then the Arc<Handler> but I can't pinpoint it. I'm fine with going with that for now.

**Comment by fleupold** [comment]
I think you are right that the LiquiditySource trait is not really needed at this point. When thinking the overall design, I designed the components with abstract concepts in mind (e.g. what have all sources of liquidity in commeo, and how could this be generalised), but I see your point that it doesn't add much value (it could make testing the LiquidityFetcher easier and LiquidityFetcher could even implement LiquiditySource on itself, but these are not really good arguments).


Regarding the vec-of-enum vs. struct-of-vec I don't really see a big usability difference. Can you give some examples where you think it would be easier to use the struct of vec? One thing I like about a vec of enum is that call-sites usually have to use a switch statement to handle each type accordingly. This means when adding a new type the compiler automatically tells us all the call-sites where we need to add some logic for the new subtype (or deliberately decide to ignore it). When using a struct of vec we are usually just accessing fields so adding a new one doesn't raise any error. This arguably only makes a difference in large codebases with many call-sites (but who knows what other logic we will perform on liquidity in the future).


 > It feels like there should be a better abstraction than the Arc but I can't pinpoint it.

One thought I had was to use a FnOnce (or FnMut), but I felt an abstract handler was a little bit easier to conceptualise than passing a closure around.

**Comment by vkgnosis** [comment]
> Regarding the vec-of-enum vs. struct-of-vec I don't really see a big usability difference. Can you give some examples where you think it would be easier to use the struct of vec?

I would guess that every solver has to match on this vector because different enum types are handled differently. So naturally it would be easier to have them separated already. I feel there is no benefit from the enum because the types don't share any common operation. To me it feels more natural then to have separate vectors. For the enum it is true that you would get a compile error (unless you added a `_` case) but that is minor and you could even achieve the same thing by destructuring the struct in the argument:

```rust
struct S {
    a: Vec<u32>,
    b: Vec<u64>,
}

fn foo(S { a, b})
```

**Comment by nlordell** [comment]
> Regarding @josojo's concern about having fundamentally different solvers

I would actually suggest having individual solver implementation take care of this:
```rust
struct SomeSolverWithOnlyLinearOrderSupport;
impl Solver for SomeSolverWithOnlyLinearOrderSupport {
    async fn solve(&self, batch: Batch) -> Settlement {
        let linearOrderICareAbout = batch.liquidity.filter_map(|liquidity| match liquidity {
            Liquidity::Amm(amm_order) => Some(amm_order.linera_approximation()),
            Liquidity::Linear(linear_order) => Some(linear_order),
            _ => None,
        });
        // ...
    }
}
```

> Is this functionally equivalent to transform_world_for_python_solver

I had originally envisioned it to be roughly equivalent for now, since this is the only "real" solver we support. I also imagined that if we did end up having multiple "real" solvers, then this would be the union of all data required by the HTTP solver's supported features and the other "real" solver's supported features (so equivalent to `transform_world_for_python_solver() ∪ transform_word_for_quantum_computer_solver()`). Essentially its just the batch data as a snapshot. Solver backends are free to pre-process/filter this before passing on the actual implementation, and was more about separating data collection, source management, etc. in the `World` from the actual batch data solver operate on.

> Regarding the vec-of-enum vs. struct-of-vec

I'm OK either way, but I slightly prefer vec-of-enums as it forces code that uses liquidity to explicitly handle/forget liquidity "types" as they get added. For similar order types, the use of "sub-types" can help bundle these liquidity types into categories to be handled together. Since adding liquidity types requires solver support, I don't expect this to happen too often so:
- I don't think it will be a big maintenance burden compared to struct-of-vecs
- Formally defines a set of "liquidity primitives" that are supported by the driver/solvers

That being said, Its really hard to gauge ahead of time which approach will work out better in the long run without a crystal ball.

>  would guess that every solver has to match on this vector because different enum types are handled differently.

I would suspect that for the HTTP solver, we would `#[derive(Serialize)] enum Liquidity` and just pass it to the solver (which can do what it wants with it). In this regard, they are all treated the same. As for the naive solver it would just `batch.liquidity.filter_map(|liquidity| match liquidity { Liquidity::Uniswap(uniswap) => Some(uniswap), _ => None })`. I really think we should optimize the code design for the current solvers, so Python solver and naive solver. If we introduce future solvers, we can always adapt these abstractions for a better fit.

> One thought I had was to use a FnOnce (or FnMut), but I felt an abstract handler was a little bit easier to conceptualise than passing a closure around (especially with regards to lifetimes and ownership).

Personally, I would just do something like:
```rust
enum Liquidity {
    Amm(AmmLiquidity),
    Linear(LinearLiquidity),
    // ...
}
impl Liquidity {
    // NOTE: Can be implemented as a macro, so it isn't so repetitive.
    fn as_interaction(&self) -> Box<dyn Interaction> {
        match self {
            Liquidity::Amm(amm) => amm.as_interaction().into(),
            Liquidity::Linear(linear) => linear.as_interaction(),
            // ...
        }
    }
}

struct AmmLiquidity;
struct UniswapInteraction;
impl Liquidity {
    fn as_interaction(&self) -> UniswapInteraction {
        // ...
    }
}
struct LineraLiquidity;
impl Into<Interaction> for Liquidity {
    fn as_interaction(&self) -> Box<dyn Interaction> { // support multiple "sub-types"
        // ...
    }
}
```

**Comment by nlordell** [comment]
>> One thought I had was to use a FnOnce (or FnMut), but I felt an abstract handler was a little bit easier to conceptualise than passing a closure around (especially with regards to lifetimes and ownership).
> Personally, I would just do something like:

Hmm, I'm not very happy about my approach :point_up: , since it starts tying required additional data required for encoding the interaction (like Uniswap pair address for example) to the solver liquidity model, which is not desirable in my opinion. The problem I also see is the the solution includes parameters that also affect the encoding (for example Uniswap in and out amounts).
