### ISSUE TITLE
Handle balances for same user with multiple sell orders for same token

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#309]
In this case we currently assume all orders are valid because they individually have enough balance but if we actually tried to settle this it would not work out.

**Comment by fleupold** [comment]
Should this be handled by the orderbook or in the solver? And what would be a sensible strategy? Should we discount balances in the order that orders were placed/are valid until?

**Comment by anxolin** [comment]
If we tackle this problem, do you think we could exposed the available balance for the current?

Depending on the browser and settings we could try to keep track of the available balance, but I think doing it in the FE will make it more unreliable and will offer worse UX.

One thing that I believe is related is, as an user, If I see my available balance is below my wallet balance, I would like to see the open orders and be able to cancel them. So for having these parts more round, I think we'll need to:
  - Handle this case: One suggestion is to deduct the balances in FIFO basis. If the user manage to send many orders somehow, he would have negative effective balance, and only the first orders would be taken into account
  - The user can see his open orders
  - The user can cancel any open order
  
  
Open questions. If we go for the FIFO suggestion above, can we include the "effectiveSellAmount" (or buy effective buy amount), for each order returned by the backend, so we know how much or if the open order is being taken into account?

**Comment by anxolin** [comment]
One other open question, if we go for the FIFO approach, does it mean we don't allow to implement unlimited volume strategies, or bracket strategies of some sort that use more volume that the one you have?

**Comment by vkgnosis** [comment]
Before figuring out how to communicate this to the frontend we should first think about how we are going to actually do it in the backend. I feel it would be useful if we didn't need to communicate this to the frontend at all in order to not make front and backend depend so closely on each other. For example the frontend could simply warn users if they are selling more of a token over all their orders than their balance and leave it unspecified what exactly happens in this situation (how the solver picks orders). We would still have an effective balance route per user and token for ease of use in the frontend.

Then we have the freedom to do what we want in the backend. Some possible choices are:
1. Prioritize earlier orders
2. Prioritize less restrictive prices (but more complex to determine when there are two sell orders of same token buying different tokens)
3. Pick randomly
4. Based on valid_to to give distinct time ranges where different orders are valid

> Should this be handled by the orderbook or in the solver?

I am inclined to say in the solver because there could be solvers that are able to handle balances. In that case we would adapt the route solvers use to fetch orders and return the list of orders and then all relevant user token balances separately.

**Comment by fleupold** [comment]
> Should this be handled by the orderbook or in the solver?

After our discussion yesterday, I actually think the balance decision will in the long run have to live in the orderbook part to allow a fair competition between solvers. Our current thinking for that phase is still that a solution will be considered "better" than some other solution if it minimizes disregarded utility (envy-freeness). It's really hard to measure envy freeness if the orderbook returns orders that are not all fillable (as Tom pointed out yesterday an order can also be disregarded because the user didn't have balance, but then it becomes non trivial to rate different choices in subsets). 

So if a user has placed many overlapping orders on a limited balance it would be nice if the orderbook decides which ones it returns for the competition.

**Comment by anxolin** [comment]
If I understand well, I agree with felix comment above. Whatever decision we take on which orders are "active" (being considered by the solvers), we should be transparent and expose it in the orderbook.

Regarding this decisions being independent of the frontend, I don't necessarily agree. It's true that each front-end can implement their logics, but it should be clear what the solvers will do in case my orders are "not active"

Not sure if this PR is the right forum, but I would love to understand and discus how to better handle:
- Alice makes a partially fillable order to sell her 100 DAI, she transfer 20 DAI to Bob `-->` I believe we should be able to tell Alice, that her order is fillable up to 80%
-  Alice makes a fill or kill order to sell her 100 DAI, she transfer 20 DAI to Bob. `-->` I believe we should be able to tell Alice, that her order is not fillable
- Alice creates an order, and before is traded, she creates another order:
   * I would love to be able to tell Alice on her second order she can't do that, that she needs to cancel her first order
   * For warning her, ideally I believe we need to be able to get her `effective balance` in the API, because she can go to any other browser/computer and do new orders. And alternatively we would be making all clients/webs to have to calculate the effective balance based in their open orders, trade amounts and wallet balances (not very feasible for a simple UI)
   * Additionally, I think the backend should refuse the second order in the case she manage to sign and post the order (a bad UI could do that), with a defined error code that would allow the UI to handle the case and inform the user.
   
For my comments above, I'm assuming we took the decision of not allowing to create orders with more than what you have. And I understood was a technical problem and that we took the pragmatic approach, but in the future we will probably want to add it, and maybe add a flag in the order to signal that you want to create orders over your balance. 
* It can be even a premium feature ;) (it cost more tip, because is more expensive for us to calculate, but is more capital efficient for them)

**Comment by vkgnosis** [comment]
> After our discussion yesterday, I actually think the balance decision will in the long run have to live in the orderbook part to allow a fair competition between solvers.

The argumentation makes sense. Still feels sad that we can't have better solvers taking balances into account but also seems like a reasonable compromise.

> Regarding this decisions being independent of the frontend, I don't necessarily agree. It's true that each front-end can implement their logics, but it should be clear what the solvers will do in case my orders are "not active"

I prefer to not set into stone how the order book does this. I feel that for the frontend it should be enough to say that users *should* only have one order selling a specific token. If users create more, then result is "undefined" as in we don't make guarantees for which orders is preferred. The frontend can check this condition and in that case not allow placing the second order or display a warning. Balances don't have to be calculated because balances aren't part of the rule.
What exactly we should enforce when creating a new order on the order book side I am not sure yet.

I can see that communicating the effective balance is important for users. This is already part of returned orders as `availableBalance`.

**Comment by anxolin** [comment]
Ok, I was not super aware of this! So `availableBalance` will tell us if it's being considered or not?
So we can actually understand if the order is executable 🚀
So yes, with this I would have most of it!

The other part I would love to consider that we add is:
* `/accounts/0x1234567890/balances/0x987654321/available`: This would simplify how the clients like webs or CLI calculate if the user can place an order (before sending it). Otherwise, we need to calculate it in the client (that is way harder), or only inform after they have sent the order (bad UX)
* (optionally, depending what the backend does) An error code in `POST /api/v1/orders` when the backend don't accept an order. So we can handle it

**Comment by vkgnosis** [comment]
> Ok, I was not super aware of this! So availableBalance will tell us if it's being considered or not?

To be clear, this is just the available balance which is not the same as "is the order being considered by the solver". Imo the best way to communicate whether an order is solvable would be to add a new bool field for this. That way whatever criterion we pick in the order book, it is always clear in the api.
How we should communicate whether an order *would* be solvable before placing it is not yet clear. Again I would like to make this independent of the specific solvable criterion which I want to be an implementation detail. We could add a flag `rejectIfNotSolvable` to the post order route which if set would make the order book reject a new order if it determines that right now it would not be solvable.

**Comment by anxolin** [comment]
> To be clear, this is just the available balance which is not the same as "is the order being considered by the solver". Imo the best way to communicate whether an order is solvable would be to add a new bool field for this. That way whatever criterion we pick in the order book, it is always clear in the api.

I like the idea. And is good if we can abstract this decisions like that. But the `bool` would be either yes/no, I wouldn't know if it's only half solvable

>  We could add a flag rejectIfNotSolvable

But `rejectIfNotSolvable` will reject based on the balance of the user and his open order, right?  (nothing to do with the price, paths or AMMs). If that's the case, I would call it `allowUncoveredBalance` (or sth that has the word balance in it)

**Comment by vkgnosis** [comment]
Let me try to summarize the discussion from my pov.

What I have been trying to say is that I would like to decouple whether an order is considered by solvers as an implementation detail we can change in the order book without making changes in the frontend. In this case it doesn't make sense to talk about effective balances because it is not balances that are important. It is <implementation detail> which we communicate only via bool.

The alternative is what you suggested in your first post. We order orders by creation_date (fifo) and have a field for the effective balance based on this ordering and total balance. That case has the advantage that the frontend can display more information about *why* orders are not considered by the solver and how to fix that "add <amount> balance to unlock <order>".

In the first case the frontend could only display a generic warning like: "your orders selling <token> add up to more than your balance <balance> which causes <these orders> to not be considered by the solver. add more balance or cancel orders to fix this". 

My opinion is that the better error message in case 2 is not worth the extra complexity and restrictiveness.

**Comment by anxolin** [comment]
> What I have been trying to say is that I would like to decouple whether an order is considered by solvers as an implementation detail we can change in the order book without making changes in the frontend. 

I thought I was following, now I'm not sure if I'm not seeing something :) 
But if I understand correctly:
* I agree on the abstraction thing. This should be only handled in the backend. It looks like an implementation detail how you choose which orders are valid
* Regarding the boolean flag, I thought it was a good idea
* ... my comment was implying that a flag, will say if the order is active or not, but maybe we have one order of 100 DAI, and the user has only 50 DAI. This is why, from my point of view is still an effective balance per order
* Note that including an effective balance don't break the abstraction. The backend decide how to split the balance of the user. It just give more details and align frontend and solver (I assume you will give a similar info to the solver)

Regarding the warnings you suggest, yes, I think something like that is the way to go.

**Comment by vkgnosis** [comment]
Maybe I have over complicated and a concrete example helps. Let's say a user has two orders selling token A for B. The user has a balance of 10 A.Order 1 sells 15 A and order 2 sells 20 A.
In this case what is the effective balance for each order? If we had a route like `/accounts/<user>/balances/<sell token>/available` it would return 10. But this doesn't allow the frontend to determine how much balance the user needs to add so that order 2 is considered because this depends on which order gets priority. If the user adds 10 balance we could either start solving order 1 or order 2 but not both.
So imo the correct way to do this is to have this account balance route per user and sell token but not have an effective balance per individual order.

**Comment by fleupold** [comment]
Maybe the endpoint could be something like `/accounts/<user>/balances/<token>/totalOpenSellVolume` and is just the sum of all open orders (which the frontend can deduct from the current balance/allowance).

Another suggestions raised here was to error when we place an order that is not immediately valid. This might make sense for DDos protections, but otherwise I don't immediately see value in it if I can always reach an invalid state late (by reducing allowance/transferring away tokens).

I personally think the availableBalance on each order should be the portion of available balance for this particular order (either 0 or sellAmount for fillOrKill, anything in between for partial fills).

I also agree that the sort criteria should not necessarily be set in stone (e.g. I think it could eventually be nice if "looser" orders replace "tighter" orders to increase chance of matching)

**Comment by anxolin** [comment]
Yep, I think the example helps. 

> Maybe I have over complicated and a concrete example helps. Let's say a user has two orders selling token A for B. The user has a balance of 10 A.Order 1 sells 15 A and order 2 sells 20 A.
>  it would return 10

I believe the endpoint should return 10 - 15 - 20 = `-25 A`
A negative number would tell us, he is trying to sell more than what he has. Also allow us to know exactly how much. 

Then, I assume the backend makes a decision using his own criteria. Should it select order 1 as fillable or order 2? Backend could use their own criteria and not expose this (i.e. creation dates, price, traded volume, generated fees, etc..)
- **Order 1**: If the backend selects order one as fillable, he would return, within the order information:
   -  `Order 1: availableBalance` = **10 A** (5 A remains unfillable)
   -  `Order 2: availableBalance` = **0**
- **Order 2**: If the backend selects order one as fillable, he would return, within the order information:
   -  `Order 1: availableBalance` = **0**
   -  `Order 2: availableBalance` = **10 A** (10 A remains unfillable)
   
  
This way, clients don't need to know how the backend chooses the orders that are being consider
Further more, I think this approach is compatible with in the future allowing to add the feature where we **consider all open orders** (as we used to do in GPv1)

I think this is also what Felix suggest here:
> I personally think the availableBalance on each order should be the portion of available balance for this particular order (either 0 or sellAmount for fillOrKill, anything in between for partial fills).

> I also agree that the sort criteria should not necessarily be set in stone (e.g. I think it could eventually be nice if "looser" orders replace "tighter" orders to increase chance of matching)

I think we all agree on this one. 

> If we had a route like /accounts/<user>/balances/<sell token>/available

It sounds good to me that endpoint

**Comment by fleupold** [comment]
> I think we all agree on this one:
   \> If we had a route like /accounts//balances//available

I find returning a negative value on available balance weird (it could seem like you are in credit and owe something to the exchange or the like). Do you have any concerns with exposing the total open sell volume and leaving it to the consumer to do the `balance - total_open_sell_volume` computation?

**Comment by anxolin** [comment]
>I find returning a negative value on available balance weird (it could seem like you are in credit and owe something to the exchange or the like). Do you have any concerns with exposing the total open sell volume and leaving it to the consumer to do the balance - total_open_sell_volume computation?

aha, I didn't get that was your suggestion. Yes its a good option!
