### ISSUE TITLE
Make orderbook maintenance HPA compatible

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v2-services#444]
At the moment, we can run into a primary key violation if two API pods are running at the same time (cf. https://gnosisinc.slack.com/archives/CQZBU9T5J/p1617221794003700).

In the [logs](https://logs.gnosisdev.com/goto/7155413645283910869a632983c2045e) we can see that two pods were operating around the time the error happened. This can happen in case we restart pods (rollin update making sure that one pod has to be fully ready before the existing one is shut down) or more likely when we use high availability auto scaling and create multiple instances of our pod (at the moment this happens on xDAI when our trading bot runs, because it's invoking a lot of price estimates).

The issue seems to be coming from the fact that we first delete all events in one transaction and then insert new events in a separate transaction:

https://github.com/gnosis/gp-v2-services/blob/afec9d968d5e0d824122f7509d42b7072c2e63fe/orderbook/src/event_updater.rs#L72-L83

This allows for race conditions in case there are two instances inserting on the same db.

One way to mitigate would be to bundle the updates in a transaction or add some other way for pods to communicate with one another to signal who is taking care of maintenance.

**Comment by vkgnosis** [comment]
The existing logic bundles events into chunks of

```rust
const INSERT_EVENT_BATCH_SIZE: usize = 250;
```

events. The deletion of all events in the range and the insertion of the first chunk happens in one transaction. It surprises me that we ran into this issue because if our assumptions are correct that means we had more than 250 events in the last 25 blocks. Alternatively
* postgres transactions don't work as we think they do and the two transactions ran at the same time
* the node returned the same event twice

I can think of these fixes:

1. Increase the batch size significantly which should make the insertions not landing in the same transaction extremely unlikely. This is an easy fix with no disadvantage as 250 I can't imagine inserting even 10k events together would be a problem.
2. Change the query so that it does not error if the event already exists. Presumably the events are identical so it doesn't matter whether they already exist. In the unlikely case that the two instances disagree on the state of the chain this would be resolved the next time the events update.
3. Do not make event updating part of HPA. HPA makes sense for the http api but it does not for updating events. We can create a separate pod that is only responsible for updating events and make the http api pod only read events.

We should definitely do 1 because it has no drawbacks. I like 3 over 2 because it is a proper solution and less of a band aid. It makes sense to only have one source of event updating and it doesn't make sense to scale this with HPA.

**Comment by fleupold** [comment]
I fully agree with your assessment. I think 1) could still cause issues on completely cold starts of the DB (e.g. after an non backwards compatible upgrade). 

3) makes a lot sense, and is probably something we can do a bit later (not super urgent as of right now)...

**Comment by vkgnosis** [comment]
I've been reading the postgres documentation for transaction https://www.postgresql.org/docs/current/sql-set-transaction.html . I don't think this error should happen even with HPA. Indeed we see the issue even when only one pod was running. I have made a local test that updates randomized events concurrently and could never reproduce this.
I have also checked the raw response node response data and didn't see a duplicated event.
Maybe one more thing to try is seeing if we can enable logs for the postgres transport so we can see the raw queries. Maybe the postgres server has logs too.

**Comment by fleupold** [comment]
> I don't think this error should happen even with HPA. Indeed we see the issue even when only one pod was running.

Can you link an example of a time where only one pod was running? From the alerts, I only see this happening around the time our trading bot runs (in which case we issue a lot of API requests and therefore usually spin up a second instance).

From the few samples I checked there was always a "parallel maintenance job" running. E.g:

![image](https://user-images.githubusercontent.com/1200333/115396341-25e0bc00-a1e5-11eb-9c71-263170c54507.png)


I have also been reading about different [isolation levels of transaction](https://www.postgresql.org/docs/13/transaction-iso.html). I think even if we chose a stricter isolation level we would run in errors of kind:

> ERROR:  could not serialize access due to concurrent update

The possibly simplest option to fix the error would be to add a `ON CONFLICT IGNORE/REPLACE` to our insert statements. Alternatively, we could first [lock the relevant table in `ACCESS EXCLUSIVE` mode](https://www.postgresql.org/docs/current/sql-lock.html) in our maintenance logic (thus making the delete + insert atomic).

Or we leave things like they are and try to inspect the error and ignore pkey violations as they are benign (I'd prefer one of the other options though).

**Comment by vkgnosis** [comment]
I think https://logs.gnosisdev.com/goto/b98ada37cd454779749fc694934f7957 only had one pod.

**Comment by fleupold** [comment]
Even there I see two pods running maintenance 3ms apart. 

![image](https://user-images.githubusercontent.com/1200333/115400860-08fab780-a1ea-11eb-80c7-01ddb6fed5c6.png)

**Comment by vkgnosis** [comment]
Ah I see, you're right. I was comparing the pod names and must have missed this because only the last 4 characters changed. My multi threaded test must have gotten unlucky or local postgres is so fast that it doesn't trigger.
If we increase the isolation level then we will probably still get errors because postgres tells us it has prevented a conflict and thus couldn't complete one of the transactions. I'll make a PR to change the insert to insert or update then.

**Comment by fleupold** [comment]
> My multi threaded test must have gotten unlucky or local postgres is so fast that it doesn't trigger.

The other possibility is that your local postgres instance is not parallelised and therefore the transactions happen in serial on even if triggered from many different threads?
