### ISSUE TITLE
Curious Possible Bug

### ISSUE THREAD

**Issue by bh2smith** [gnosis/gp-v2-services#452]
After placing an order today I noticed that the `receiver` field in the order record was not set to null but rather the zero address. I really hope this doesn't mean the zero address will be the fund receiver when the trade goes through.

Is this a result of #447?

<img width="720" alt="Screenshot 2021-04-07 at 13 01 35" src="https://user-images.githubusercontent.com/11778116/113856486-99c0a480-97a1-11eb-84ce-f47fdd155886.png">

**Comment by vkgnosis** [comment]
It's intentional. In the contract there is no None or Null so the default receiver (the signer) is represented as all zeroes. Even if we had a bug that caused the database to store wrong receivers that should cause signature verification to fail in the contract otherwise it would be a huge security issue.

**Comment by nlordell** [comment]
I discussed this with @anxolin briefly and he suggested populating the `receiver` field with the signing owner's account address instead of 0's. This costs 240 additional gas (because of non-zero calldata) but avoids this kind of confusion.

**Comment by vkgnosis** [comment]
It's a frontend decision but if the smart contract has defined these semantics (0 means signer) and it saves gas then I prefer not setting it.

**Comment by nlordell** [comment]
Closing in favour of https://github.com/gnosis/gp-swap-ui/issues/394
