### ISSUE TITLE
Recover orders for which there is only a trade event

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v2-services#463]
It's possible that we see a trade event without having seen the order being placed via our API beforehand (e.g. some "private liquidity" is used or simply the order was placed via our staging endpoint, so the prod endpoint didn't see it).

We should still be able to recover the order creation data and most of the order metadata (except for creation timestamp) just from looking at the calldata of the transaction that created the event.

Creation timestamp could become a "first seen" timestamp and just set to now() in that case.

**Comment by fleupold** [comment]
@anxolin suggested that the field could also be made nullable (instead of using a fake timestamp of the trade event)

**Comment by anxolin** [comment]
Thanks! Just bringing my comment in, since I'm OK with both options:

Regarding the creation time, if we don’t have that info, is not as important as having coherent environments. Options for that are:
- Making that nullable: Then we could optionally make a ETL that would reconciliate this date (at least one env must have it).
- Making that date to be the time of the block of the first trade of the order. Although is not “pure”, this could be good enough, at least as a start
