### ISSUE TITLE
Suppress transaction revert errors for `UniswapV2Router: INSUFFICIENT_OUTPUT_AMOUNT`

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#527]
When a transaction simulation succeeds, but then proceeds to revert with `UniswapV2Router: INSUFFICIENT_OUTPUT_AMOUNT`, we should suppress the alert and simply use Prometheus metrics to count this:
- This would give us a better overall picture of how many transactions revert because of price movement
- Reduces noise in the alerts channel.

**Comment by fleupold** [comment]
I think this is a good suggestion! I'm wondering if we could implement something even more generic (that would work for race-conditions on arbitrary liquidity) by recording/fixing the block at which the liquidity sources were queried. If we then successfully simulate the solution on that block but fail to simulate it on "latest/pending", it's pretty clear that we have a race condition.

Conversely, if we can't even simulate it on the fixed block we either have a bug in our solver or the token pair is not supported (e.g. because it takes a transfer fee or the like).
