### ISSUE TITLE
Get AMM current state

### ISSUE THREAD

**Issue by josojo** [gnosis/gp-v2-services#67]
In order to calculate solutions that contain trades against AMM, we need to get the current balances of them and feed this into the naive solver.

**Comment by fleupold** [comment]
At least the way the naive solver is written right now, this is not necessary. The solver computes the min out amount and we can simulate the call (of it fails, it's possible, otherwise not). I agree this is needed for a more sophisticated settlement (where we trade an arbitrary number of orders on one token pair against each other + AMM).
