### ISSUE TITLE
Paraswap buy orders and slippage

### ISSUE THREAD

**Issue by josojo** [gnosis/gp-v2-services#788]
Currently, we have the following logic for buy orders in parawasp solver
```
// 0.1% slippage
        let dest_amount_with_slippage = price_response
            .dest_amount
            .checked_mul(999.into())
            .ok_or_else(|| anyhow!("Overflow during slippage computation"))?
            / 1000;
        let transaction_query = TransactionBuilderQuery {
            src_token: order.sell_token,
            dest_token: order.buy_token,
            src_amount: price_response.src_amount,
            dest_amount: dest_amount_with_slippage,
   ```
   Hence, to my understanding, the user might not get the specified buy amount, due to the fact that we build in the slippage. To my understanding, we should increase the src_amount by 0.001% for buy orders, instead of reducing the dest_amount. 
   Or do I miss something?

**Comment by nlordell** [comment]
Since Paraswap supports buy orders, we should probably exclusively use them (like we do with Uniswap) and therefore apply slippage by increasing the source amount. This would make slippage get taken from the fees and make the settlement less likely to fail overall (since the settlement will always have buffers in that token in the form of fees it just collected).

**Comment by fleupold** [comment]
This is a very good observation and likely the real reason for these 

> {"error":"Destination Amount Mismatch"}

Looking at this query (https://logs.gnosis.io/goto/8517bf2e40c67149966b6fd8a53e159e) buy orders and the error messages line up perfectly

**Comment by josojo** [comment]
Nice! 
Felix, if you want I can do the code changes. I have them kinda done already for matcha

**Comment by nlordell** [comment]
Do you think its worth discussing:

> Since Paraswap supports buy orders, we should probably exclusively use them

We already use buy orders exclusively with Uniswap, as well as the Balancer interaction is based on this as well, as it works better with the clearing price mechanism we use in settlements. Mainly this is beneficial since it allows the input about for the trade to move a bit meaning that:
- We will always be able to pay out the buy amount to the user, even in the event of small price movements. This isn't true if we use sell orders buying token for which we have 0 buffers
- Slippage can be absorbed by the order fee.

**Comment by fleupold** [comment]
It's definitely worth discussing 😄 

The challenge will be translating the user's sell order into a buy order (in order to get the correct BUY transaction payload).

If I understand your proposal correctly, we would
- query the bestRoute (price estimate) for the sell order of the user, which yields us a destAmount
- query the bestRoute again for a fixed destAmount (buy order equivalent of the sell order)
- If srcAmount of the second query is roughly equal to srcAmount of first original sell order, we request the transaction payload for that buy order

**Comment by nlordell** [comment]
Ah, we would need to query the API twice - that's unfortunate.
