### ISSUE TITLE
Add health check endpoint

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#885]
Today we saw that the driver run loop did not continue running for reasons we don't know yet. The pod on the whole was fine and continued to emit debug logs but the run loop did not progress.
One way to detect and automatically react to this would be to expose a health check endpoint which could record the last time the driver started a run loop. If the time is older than X we could automatically restart the pod.

**Comment by fleupold** [comment]
My suggestion would be to add another method to the [`SolverMetrics`](https://github.com/gnosis/oba-services/blob/9b409b1d2de22fcaa63adf601c9dce61ddc51697/solver/src/metrics.rs#L21) trait (something like `runloopCompleted`) and then just store a timestamp of the last time the runloop completed.

We could then add a `handle_liveness` warp filter to our [metrics module](https://github.com/gnosis/oba-services/blob/9b409b1d2de22fcaa63adf601c9dce61ddc51697/shared/src/metrics.rs#L15) which would take a simple trait:

```rust
trait LivenessChecking {
  fn is_live(&self) -> bool;
}
```

which `Metrics` can implement by computing the difference of now() and the last time runloopCompleted was called. If below some threshold (I'm thinking 7 minutes: 5 minute solution submission timeout + 1 minute solving + 1 minute buffer) it returns 200, otherwise 500.

If no-one else wants to do this, I can try implementing this tomorrow (looks like I have some free coding time in the morning).
