### ISSUE TITLE
Handling contracts upgrade with regards to database

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#891]
The order struct as of alpha 15 which is what we currently use in services is

```
    struct Data {
        IERC20 sellToken;
        IERC20 buyToken;
        address receiver;
        uint256 sellAmount;
        uint256 buyAmount;
        uint32 validTo;
        bytes32 appData;
        uint256 feeAmount;
        bytes32 kind;
        bool partiallyFillable;
    }
```

The order struct in version 1.0 which is what we want to upgrade to contains the extra fields

```
        bytes32 sellTokenBalance;
        bytes32 buyTokenBalance;
```

Like `kind` these are semantically enums and would be stored as such in the database instead of as bytes. The valid values are BALANCE_ERC20, BALANCE_EXTERNAL, BALANCE_INTERNAL.

How do we want to model this in the database and in our Rust Order struct?

1. If we want to stay backward compatible we could store the new fields as an Option which would be none for old orders (null in the database) or we could add a new placeholder enum value like LEGACY_ORDER which would be set for all old orders.
2. Alternatively we could create a fresh table for the new order format and keep old orders only in the old table (or drop them).

1 has the advantage that it allows us to treat old orders mostly as if there were new orders. They wouldn't be solvable but for other purposes they behave the same way. This is good because the gpv2 explorer can continue to display information for old orders and we can write queries for the referral program without specializing them for old orders.
It has the disadvantage that it makes the type system a little weaker. Old orders have their signatures calculated in a different way and if we only had new orders then we wouldn't need the extra null or placeholder enum value. This means having some places in the code check whether this is an old or new order and react differently.

Having summarized this now I feel 1 is the better choice.

**Comment by fleupold** [comment]
Instead of setting it to null we maybe could also set it to "BALANCE_ERC20" by default (since this is what legacy orders effectively are). The migration framework should allow for this update.

However, I'm not sure if it might be better to have some indication of legacy vs. new order format to have more explicit expectations why signature verification may fail.

**Comment by nlordell** [comment]
> However, I'm not sure if it might be better to have some indication of legacy

One idea is to either keep a version number column (so original contract would be version `0`, the upgraded SC would be version `1`).

Alternatively, we could also add a column for GPv2 the contract address the order was created for. The advantage of this is that we don't need to worry about manually keeping track of a version number, remembering to bump it everytime the contract changes. Additionally, it is not sufficient to bump this version number only on version changes, since the domain separator used in the signature includes the contract address, so even if we do have a contract upgrade where there are no changes to the order data, the signature would still be invalid.

**Comment by bh2smith** [comment]
I feel like the contracts upgrade has already been taken care of... #940
