### ISSUE TITLE
External prices used in the driver are incorrect.

### ISSUE THREAD

**Issue by marcovc** [gnosis/gp-v2-services#950]
In this [instance](http://gnosis-europe-dev-gpv2-solver.s3-eu-central-1.amazonaws.com/data/dev/2021/08/06/13%3A23%3A10.517679630_UTC_Ethereum_1/00_instance_raw.json) collected today, the external price of SNX was given as 0.37783117020632184 WETH. The price of SNX today according to trading view is 0.0037 WETH. 

This is more serious than it looks. It is not just the value passed to the MIP solver that is wrong (we're even currently discarding it), but more importantly, this external price is used in the driver to rank solutions. For this particular instance, the winning solution was wrongly the NaiveSolver one, settling 2 orders instead of potentially 12 by quasimodo. 

The surplus [reported](https://logs.gnosisdev.com/app/kibana#/discover/doc/de1f5360-a9ae-11ea-acbb-9d2e3cb124ca/logstash-2021.08.06?id=HJSiG3sB4_N2vXHsD_9I) by the NaiveSolver does not match the surplus I get using the MIP solver to solve the same 2 order instance (it differs by an order of magnitude).

**Comment by marcovc** [comment]
Added a branch to help debugging this. There I simply ask for the spot price of DAI in WETH using the baseline solver, which is as far as I understand, what is used to compute the external prices.

Just fire the driver, and compare the result printed on screen with what you get on uniswap. E.g.

```
Ok(([0x6b175474e89094c44da98b954eedeac495271d0f, 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48, 0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2, 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2], Ratio { numer: 794988755323177770059104715404179248159523760, denom: 1784698508791318728305668945601308162448044388861 }))
```

means that the price of DAI is `0.00044544708891003745 WETH`, but on uniswap v3 I get `0.000333583`. I know that we don't use uniswap v3 in the baseline solver, but I don't think 25% difference could be explained by that.

**Comment by vkgnosis** [comment]
We discussed this on [Slack](https://gnosisinc.slack.com/archives/CC3C5SMB5/p1628525146015300).

The cause for the issue is that spot price estimation uses a 0 amount which makes it consider small pools that can change the price significantly because they are out of sync with the bigger pools that would actually be used to settle.
To fix this we should exclude small pools from our price estimation (which uses the baseline solver). A reasonable way to define small would be that the total value in the pool is less than 1 eth. Every token must have a connection to the native token through the base tokens so this should be enforceable. Might need to make the threshold configurable for xdai.

**Comment by marcovc** [comment]
I feel this is a critical issue that should be addressed ASAP. 

Additionally, to be able to fine tune the solver, it would be great to understand where it stands in relation to the other competitors, and is possible that this issue may skew results.

If you guys don't have time, I could try to do it myself (I think the proposal suggested by @vkgnosis should be fairly easy to do).

cc/ @nlordell 

Wdyt?

**Comment by vkgnosis** [comment]
Could also be solved by using quasimodo for price estimation as we discussed on slack. Although you'd have to decide the same problem there (what amount do you use when estimating prices). Unless in that case we would still do the exclusion on the rust side.
Doing this through excluding small pools is a little harder than expected I think after looking at the code. That is because we don't have a list of pools stored somewhere. Instead we fetch them on demand when estimating a price (price_estimate.rs). So it is not clear how that fits in.
Maybe a simpler fix until we know how quasimodo for price estimation will fit in is to change the instances of `price_estimator.estimate_prices(tokens.as_slice(), self.native_token)` in http_solver and driver with a special function that uses a 1 eth amount instead of the 0 amount that `estimate_prices` currently uses. That way we don't have to solve the general problem for all pools (although that would still be nice for frontend prices).

**Comment by marcovc** [comment]
> Instead we fetch them on demand when estimating a price (price_estimate.rs).

**Comment by vkgnosis** [comment]
On second thought it seems feasible to do it around `price_estimate.rs:322`. There we have all the relevant pools (two tokens that we want price between + base tokens). So we should be able to do it there.

**Comment by marcovc** [comment]
I'm having second thoughts about the simple approach. 

It seems I cannot get around the chicken-and-egg problem: I thought we could do something like:

1. start with a set of "priced" tokens {native_token}
2. find a token not on the set for which there is at least one pool that has its other token priced. If this pool has enough liquidity then use it to price the new token. Repeat 2.

One problem is that in 2 we are only using one of the tokens to decide if the pool has enough liquidity. If the pool is an outlier, it can happen we believe it does just because the priced token is mispriced. Another problem is how to break ties in both selecting the next token, and selecting the best pool when there are several for the same token.

So unless you see a clean solution for this, I suggest instead to move forward and create an "HttpPriceEstimator" that calls a "estimate_prices" endpoint in our solver, since there we have a better solution for this problem.

**Comment by vkgnosis** [comment]
>  just because the reserve of the priced token is too high compared with the unpriced reserve

I see. I don't have a good solution for those problems. You could still try what I suggested earlier to estimate prices with 1 eth instead of a spot price. This is only a couple of lines of code to change.

**Comment by marcovc** [comment]
> You could still try what I suggested earlier to estimate prices with 1 eth instead of a spot price.

Cool, let me try that.

**Comment by marcovc** [comment]
Seems there is another chicken-and-egg problem [here](https://github.com/gnosis/gp-v2-services/blob/main/shared/src/price_estimate.rs#L260-L262). If we leave it at zero, then a pool with low liquidity can be chosen to set the buy token price. If we use 1  eth there it enters in infinite recursion. 

I've tried leaving this at zero while changing the sell amount to 1 ETH on the estimate_prices and the results are even worse. Do you see any other easy fix?

**Comment by marcovc** [comment]
I'm slightly confused about what I'm observing, maybe I am missing something. Take these examples:

SUSHI
* Uniswap v2 app, effective price for 1 ETH: 0.00397
* Current code (computes using spot prices): 0.007582
* Altered code computing the effective price of 1 atom of ETH: 0.00391  <---- seems to be correct
* Altered code computing the effective price of 1e18 atoms of ETH: 0.0041 <--- seems to be correct

UNI
* Uniswap v2 app, effective price for 1 ETH: 0.00847
* Current code (computes using spot prices): 0.01151
* Altered code computing the effective price of 1 atom of ETH: 0.00813 <--- seems to be correct
* Altered code computing the effective price of 1e18 atoms of ETH: 0.010832863509066294 <--- too high!

COMP
* Uniswap v2 app, effective price for 1 ETH: 0.1357
* Current code (computes using spot prices): 0.18845570695459885
* Altered code computing the effective price of 1 atom of ETH: 0.14285714285714285 <--- seems to be correct
* Altered code computing the effective price of 1e18 atoms of ETH: 0.2632492997099473 <--- too high!

So my questions are:

1. Why is there different code to compute the spot price since that is theoretically the same as computing the buy amount for one atom of the sell amount? I see one uses fees and integer arithmetic, is that it?
2. Why is that computing the buy amount for selling 1 ETH (not 1e-18 ETH!) does not return the same value as the uniswap v2 app since the system is supposed to integrate uniswap v2 liquidity?

**Comment by marcovc** [comment]
@fleupold I guess you wrote the code, perhaps you can clarify the above?

**Comment by nlordell** [comment]
> Why is there different code to compute the spot price since that is theoretically the same as computing the buy amount for one atom of the sell amount?

I don't think it is because of integer rounding. Specifically, if you compute the output amount in WBTC of 1 atom of WETH, you will likely get 0 (as WBTC is worth a lot more then WETH). Additionally, trading 1 atom also incurs the 0.3% Uniswap Fee.

> Why is that computing the buy amount for selling 1 ETH (not 1e-18 ETH!) does not return the same value as the uniswap v2 app since the system is supposed to integrate uniswap v2 liquidity?

This could be because of routing? Just guessing.

**Comment by marcovc** [comment]
>This could be because of routing? Just guessing.

Do you think rounding can explain a relative error of 100% when welling a quantity as high as 1 ETH (see COMP example)?

**Comment by vkgnosis** [comment]
Sorry, I forgot that we also have the 0 amount spot price there. I don't understand the price estimation code that well so I can't answer your questions without manually debugging it.
Another point in favor in using more advanced price estimation not implemented in the rust code. Or we can think about how the rust one can be improved but if the goal is to move to the advanced one eventually anyway then that might be wasted effort.

**Comment by marcovc** [comment]
I'm not sure anymore that using spot prices is the only problem here. As an example, trading 1ETH for DAI on uniswap v2, using just the WETH-DAI pool, gives me a lower *effective* price of DAI on the interface than the spot price returned by the current code. I can't understand how can this be.

**Comment by fleupold** [comment]
> Why is there different code to compute the spot price since that is theoretically the same as computing the buy amount for one atom of the sell amount?

The main argument for using the spot price (amount 0) rather than the prices for selling 1 atom or 1 base unit (10^18 atoms in most cases) is the LP fee. When using amounts, the ETH<>USD price will have a spread of 0.6% (0.3% off spot price in either direction). My initial thought was that just using the "spot" price (without LP fees) could work well (it turns out it doesn't).

> Why is that computing the buy amount for selling 1 ETH (not 1e-18 ETH!) does not return the same value as the uniswap v2 app since the system is supposed to integrate uniswap v2 liquidity?

We also have other liquidity integrated, maybe it would be good to print the addresses (or human readable info) of the pools that get chosen. Is the price we are computing better or worse than what Uni shows (I only see that it's off by a lot but don't know in which direction, i.e. what your specific request was)? If it's better, it could be that we find some small pool somewhere that has a good prices but just for a small amount of tokens (due to high slippage).

> Uniswap v2, using just the WETH-DAI pool, gives me a lower effective price of DAI on the interface than the spot price returned by the current code.

If I read the [current code](https://github.com/gnosis/oba-services/blob/8d46634f25c163eee8349b79e70cf46e40ff9c43/shared/src/baseline_solver.rs#L123) correctly, we try to find the maximum spot price, thus larger being "better". Maybe we need to invert the ordering in which we query the price (swap base/quote token). The issue with multiple pools is that there is not a single price and which one you prefer (highest or lowest) depends on the direction you are looking.

An alternative approach could be to buy and sell a "reasonable" amount of ETH for the target token and take the mean price as the current "spot"? This way we wouldn't get fooled by small pools.

**Comment by marcovc** [comment]
> We also have other liquidity integrated, maybe it would be good to print the addresses (or human readable info) of the pools that get chosen. 

I was running the local driver with only Uniswap liquidity to make sure.

> (I only see that it's off by a lot but don't know in which direction, i.e. what your specific request was)

Here's a [branch](https://github.com/gnosis/gp-v2-services/tree/fix-external-price-estimation) where this can be replicated. The driver will print the spot price, the effective price when selling 1 atom of eth, and the effective price when selling 1 eth, and then exit. Then compare it with uniswap v2 price for selling 1 ETH. I'm running it like this:

```
cargo run --bin solver --     --base-tokens '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0x6B175474E89094C44Da98b954EedeAC495271d0F,0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48,0xdAC17F958D2ee523a2206206994597C13D831ec7,0xc00e94Cb662C3520282E6f5717214004A7f26888,0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2,0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599'     --log-filter error     --orderbook-url https://protocol-mainnet.gnosis.io/api/v1     -k '0x0000000000000000000000000000000000000000000000000000000000000001'     --solvers Quasimodo     --node-url 'https://staging-openethereum.mainnet.gnosisdev.com'     --baseline-sources Uniswap     --fee-subsidy-factor 0.2     --gas-estimators 'GasNow,GnosisSafe,EthGasStation,Web3' --amount-to-estimate-prices-with=1
```

> If I read the current code correctly, we try to find the maximum spot price, thus larger being "better"

I was reading it as the path that leads to a higher buy amount (at least the compare function on that max_by seems to be comparing amounts, not prices).

> An alternative approach could be to buy and sell a "reasonable" amount of ETH for the target token and take the mean price as the current "spot"? This way we wouldn't get fooled by small pools.

Yeah, that is what we were trying to do (where "reasonable" = 1 ETH). Unfortunately that gives a large overestimation of the price.

**Comment by fleupold** [comment]
I took a look at the branch. The reason that buy 1ETH vs 1 wei of ETH were so off is because in rust

`"1000000000000000000".into()` results in 4722366482869645213696 since Default string parsing for U256 in rust is hex based 🤦 

The reason the spot price is off is what I before, it tries to maximize the price without respect for slippage and therefore happens to find some exotic path (for DAI -> WETH the path is DAI -> MKR -> USDC -> ETH, with MKR<>USDC pool having 17c of liquidity).

I had a sync with @marcovc and we concluded that taking the mean of "price to buy 1 ETH for token" and "price to sell one ETH for token" is a good proxy for the spot price.
