### ISSUE TITLE
Pagination on trades and orders calls

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-v2-services#969]
Add pagination to API for both trades and orders calls:

GET /api/v1/orders
GET /api/v1/trades

API should accept an optional parameter `pageSize` stating how many results should be returned at a time. Defaults to `10`.
API should accept an optional parameter `page` stating which is the current page being requested. Defaults to `0`.

## Proposal

`pageSize` must be an integer within the range (inclusive) from 1 - 100
When not set, set to a value outside of the range or an invalid value (undefined, 1.3, `gibberish`, etc), it should default to `10`

The API - to protect itself - should not allow to force-request all db values at once.

The response will probably have to change to include metadata regarding the pagination.
Instead of returning a flat list of results, it'll have to change to something like:

```json
{
  "results": 2123,
  "page": 3,
  "pageSize": 50,
  "results": [{}, ...]
}
```

**Discussion:** 
- We could allow higher `pageSize`, 100 is a conservative proposal
- We could set a higher default `pageSize`, no strong reason to keep it at 10
- The change in the response is a breaking change. Any suggestions to make the transition smooth? Deploy an extra endpoint, alter the response based on a request flag, etc.
- I based the pagination "design" in the most common pattern, but I'm not entirely sure how that would work given that the primary keys are non sequential. Instead of an integer could the page be a sort of db "cursor"?

**Comment by vkgnosis** [comment]
I started looking into pagination from the DB's perspective last week. In order to make it efficient we have to use a model where for each query there is a cursor which is based on an index in the database. For example for when querying orders this is the order uid. When you request a page you say: give me the next page of data starting after order uid X. X is the last order uid you got in your previous response page.
This is efficient because this index is ordered so Postgres can quickly find the starting point of any value in the index. It might become more complicated in some places where we have extra filters or we might need an extra index. Still have to check this for all queries.
We have to figure this out first before we can design the api.

For backward compatibility we can create a /v2/ route for the first time, see how many requests we still get to /v1/ and remove them after a week or so.

**Comment by alfetopito** [comment]
> When you request a page you say: give me the next page of data starting after order uid X. X is the last order uid you got in your previous response page.

Yes, exactly what I had in mind :)

Do you know already what's needed to get this working?

**Comment by vkgnosis** [comment]
I am still in the process of investigating the queries I create with postgres tools to see if they do what I want them to. I'd like to create the PR to adjust the queries myself since I've been working on this already.

**Comment by alfetopito** [comment]
I have a draft with what I have in mind https://github.com/gnosis/gp-v2-services/pull/978
If that's in conflict with what you are doing I can stop and wait for you.

Regarding the DB cursor approach, it didn't look like a good idea to me in the end because you need to keep a connection and a transaction open on the DB in order to use it (used this as reference https://www.citusdata.com/blog/2016/03/30/five-ways-to-paginate/).
So the ORDER BY/LIMIT/OFFSET seems like a good enough option.

**Comment by vkgnosis** [comment]
We can't do offset because it is inefficient. The page you link calls the approach I want to do "Keyset Pagination". That is stateless so it doesn't require any persistent db connection.

**Comment by alfetopito** [comment]
Ah I see.
The difference from my naive approach is that it needs an index based on a numeric key.
Ok, waiting for your approach to come out first.

**Comment by fleupold** [comment]
Does the UI just want to have infinite scroll / filtering or does it also want to jump to arbitrary intermediate pages? Asking, because that might be hard with the cursor approach (other than that I think it's a really good solution)

**Comment by alfetopito** [comment]
> Does the UI just want to have infinite scroll / filtering or does it also want to jump to arbitrary intermediate pages?

Neither.

![screenshot_2021-08-17_10-03-38](https://user-images.githubusercontent.com/43217/129769778-a4016ad6-b1db-4921-8b4a-b2079c8871f3.png)

Page by page, sequentially loaded.

But anyway, as far as I understood, the "Keyset pagination" allows for arbitrary intermediate pages as well without any issues.

**Comment by vkgnosis** [comment]
Staying with the order example it allows starting a page at any arbitrary order uid. But you wouldn't know in advance which order uid to use to get to "page 6" order "order number 300". You have to know the previous page to get the next one.

**Comment by alfetopito** [comment]
> You have to know the previous page to get the next one.

Hmm ok. Understood.
Not a problem for our current use case.

**Comment by vkgnosis** [comment]
Is this page only going to query orders and trades for a single user?

After testing more I'm starting to realize that the situation becomes a lot more complicated when you take into account the different filters we allow to be set on orders. For example if we do keyset pagination on order uid but also filter on sell token then internally the query might still have to scan the whole order database to find such an order. Or if we use the order owner index as we it have currently defined it is (if I read the postgres docs right) not able to efficiently provide an ordering on uid.  And it becomes more complicated again if you set multiple filters.
To fix these cases we'd have to plan in more detail what queries we expect and how we want to set up the indexes. This is a lot of work and not a valuable use of time at the moment based on our current amount of data and the rate it grows at. Especially if we are going to only query a single user then a sequential scan on the simple index of this user's orders is going to be fast and much easier to implement.

Based on this I would like to go with your initial PR that uses a simple offset + limit in the query.

--- 

I would reflect this in the api as follows:
Request : Extra parameters offset and page size
Response: Array of results like already is

For the first request an api user specifies offset = 0. Then they look at the response. If the response contains page_size elements then they make another request with offset += page_size and repeat. If the response contains less than page_size elements then they know they've exhausted all results.

I prefer using the offset directly because the page abstraction doesn't add value here. Offset is more flexible and represents exactly what the database does.
It also simplifies the response because we can keep it the same as it is now without needing any extra data. The api user keeps track of everything so there is no need to echo it back.

**Comment by alfetopito** [comment]
> Is this page only going to query orders and trades for a single user?

In the short term yes, but we plan to have in the future a screen with the latest orders on the protocol.

> Based on this I would like to go with your initial PR that uses a simple offset + limit in the query.

I'm onboard with that idea, for giving us a solution for the short term with relatively small impact in the existing query.
Also, given that the amount of orders is small for individual users (<1000), I don't expect many pages per query, so the wasted time on sequential pages would be negligible.

----

 > For the first request an api user specifies offset = 0. Then they look at the response. If the response contains page_size elements then they make another request with offset += page_size and repeat. If the response contains less than page_size elements then they know they've exhausted all results.
> I prefer using the offset directly because the page abstraction doesn't add value here. Offset is more flexible and represents exactly what the database does.
> It also simplifies the response because we can keep it the same as it is now without needing any extra data. The api user keeps track of everything so there is no need to echo it back.

While I understand how that works, I'm not 100% sold on this approach.
For one, it puts the burden of dealing with pagination on the caller.
And second, it binds too closely to the DB. I rather have them independent so DB/index/query changes do not break the contract with API consumers.
Of course that's me being a hypocrite, since the changes that I propose would break the current contract :sweat_smile: 

> For the page size it should always be specified and not default to anything. If the page size is not specified, too large, invalid etc the api should return an error. We would document in the openapi docs what the largest acceptable page size is.

So you propose to make `page_size` a required parameter? This is another breaking change that I think we could avoid, but I'm ok adding it.

On that note, what do you think could then be the page size limit?
Last I worked with this kind of thing it was with DynamoDB and the [limitation is response size which is up to 1MB](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.Pagination.html)

**Comment by vkgnosis** [comment]
> In the short term yes, but we plan to have in the future a screen with the latest orders on the protocol.

If it is just latest orders then we can easily make a fast query again. Only problem is all orders with additional filters like sell_token.

> So you propose to make page_size a required parameter? This is another breaking change that I think we could avoid, but I'm ok adding it.

The new api only makes if consumers know how to handle pages so it's fine. We could default it but we don't gain anything because consumers would unknowingly only get a fraction of the data. I prefer if it is explicit and fails if it's missing.

> And second, it binds too closely to the DB. I rather have them independent so DB/index/query changes do not break the contract with API consumers.

What do we gain with the page abstraction instead of offset? It is not higher level or more general than offset, it is just different. And it doesn't map to what the DB does so I feel there is no advantage. For this kind of api I don't think it is a problem that it is somewhat aligned with the DB. We have to consider what kind of queries can be efficient and only support them. If there is an easy way to make a query more resilient to internal changes we should go for it but I don't think it is the case here.

> For one, it puts the burden of dealing with pagination on the caller.
I don't think this is the case. In the page example the caller has to increment the page number. In the offset example the caller has to increase the offset by the page size. The caller will always have to deal with pagination in some way.

> On that note, what do you think could then be the page size limit?

The reason I initially looked into pagination was to make it possible to retrieve all orders. Currently we have disabled querying all orders because it would return them all in one request which is a lot of work for the database and creates a big a response. I don't think there is a limit to the size of the response but one order is 1018 bytes in json form. 
Now that I write this I realize that if we restrict ourself to per user orders we could get away with no pagination at all. Frontend could keep using the existing api withe filter on the owner (same for trades). Should we do this? Then we can plan in more detaill what queries we are going to need, how they can be efficiently paginated etc without blocking this frontend feature?

**Comment by alfetopito** [comment]
> > In the short term yes, but we plan to have in the future a screen with the latest orders on the protocol.
> 
> If it is just latest orders then we can easily make a fast query again. Only problem is all orders with additional filters like sell_token.

We might have that if we do pages for individual tokens, similar to what Etherscan has, but I don't think that's is planned now.
cc @anxolin @biocom 

> > So you propose to make page_size a required parameter? This is another breaking change that I think we could avoid, but I'm ok adding it.
> 
> The new api only makes if consumers know how to handle pages so it's fine. We could default it but we don't gain anything because consumers would unknowingly only get a fraction of the data. I prefer if it is explicit and fails if it's missing.

Makes sense

> > And second, it binds too closely to the DB. I rather have them independent so DB/index/query changes do not break the contract with API consumers.
> 
> What do we gain with the page abstraction instead of offset? It is not higher level or more general than offset, it is just different. And it doesn't map to what the DB does so I feel there is no advantage. For this kind of api I don't think it is a problem that it is somewhat aligned with the DB. We have to consider what kind of queries can be efficient and only support them. If there is an easy way to make a query more resilient to internal changes we should go for it but I don't think it is the case here.
> 
> > For one, it puts the burden of dealing with pagination on the caller.
> > I don't think this is the case. In the page example the caller has to increment the page number. In the offset example the caller has to increase the offset by the page size. The caller will always have to deal with pagination in some way.

Ok, you convinced me, let's go with that option.

> > On that note, what do you think could then be the page size limit?
> 
> The reason I initially looked into pagination was to make it possible to retrieve all orders. Currently we have disabled querying all orders because it would return them all in one request which is a lot of work for the database and creates a big a response. I don't think there is a limit to the size of the response but one order is 1018 bytes in json form.
> Now that I write this I realize that if we restrict ourself to per user orders we could get away with no pagination at all. Frontend could keep using the existing api withe filter on the owner (same for trades). Should we do this? Then we can plan in more detaill what queries we are going to need, how they can be efficiently paginated etc without blocking this frontend feature?

What do mean you by no pagination at all?

I still think this is necessary for some use cases, such as:

1. For the affiliate program, we want to check whether a user is new or returning.
We do a simple check and query the trades endpoint. 1 trade is enough to tell, I don't need to get all user's trades, so the `pageSize` would be `1`. 
In effective db query speed the improvement would be marginal, but thinking about users with lots of trades and/or slow connection that could help.

2. For the recent activity tab on cowswap, we intend to show the latest 10 orders. We don't need them all. Basically same usecase as point above

3. For the user details page on the Explorer, we want to show user's trades and orders in different tables.
For users with few trades (most of them) single call should suffice, but users with many, this can be frustrating, having the page slow to load and parse all the results.

In all of those cases, we'll be querying for orders/trades by owner, sorted by creation date, descending.

We'll have additional filters, such as: order status, selltoken, buytoken, probably date range.
We'll have sorting by date, status.
For those (filters and sorting), not clear whether they will be done client or server side.

**Comment by vkgnosis** [comment]
> What do mean you by no pagination at all?

I meant that for a single user it might be fine to not have pagination because the total amount of data would be small. Getting 10k orders is probably not a lot slower than getting 10 (but haven't measured). Anyway I don't mind adding pagination for this just and we should eventually for sure. Was just saying so you can prototype this in frontend we could forego pagination (you can fetch all user orders without pagination with the existing api). That way you can already make the UI and test it with real data and later we will change the internals of how the orders / trades are fetched to add pagination. But it's fine if we do it immediately.

> For those (filters and sorting), not clear whether they will be done client or server side.

The problem with doing it client side is that you need to fetch all the data (all pages) before you can sort. This is the same problem I was describing which happens internally in the database. If we don't have an index for the exact query (for example sort by creation date) then even with pagination the database still has to process all entries in order to build the page. Which means you save on the transfer from the db to the backend and backend to frontend but not on computation within the db.

Based on this and the use cases I think that the creation date is the most important thing to index. If we decide that orders are *always* retrieved ordered by creation date we can build efficient queries again that follow the keyset pagination approach. This makes sense from a user perspective because to them the creation time is the most natural ordering. Results might be filtered on different things but always ordered on creation date.

Filtering should *probably* be done in the DB. Imagine the case where the user has one very old order that is still open (with a very long valid_to) and then a bunch of new already closed or expired orders and we want to filter on open orders.
If we did filtering in the frontend it would have to fetch and process all pages until it finally arrives at the last page which contains the only open order. This would take a long time for the many roundtrips.
Filtering in the DB isn't efficient either because it runs into exactly the same problem but at least we save the roundtrips and transfer of the pages the frontend isn't interested in.

**Comment by alfetopito** [comment]
Agree on having pagination based on creation date, descending (latest first).
Unless there's another use case that asks for them being ascending?

**Comment by vkgnosis** [comment]
I want to clarify something about the user trades endpoint. In the meeting we said we should include full order information with the trades. Looking at this I wonder if you need everything from the Orders struct or only a subset like sell and buy token. In that case I'd like to only return that subset and not the full order.
The reason is that the order struct has accumulated a lot of stuff over time that is a little hairy to fetch. For example it feels wrong that we would first get a page of trades and then in order to get the orders have to fetch a bunch more trades to calculate the full remaining balance of an order (for a partially fillable order) because that information is part of the order struct even if it might not be needed here.

**Comment by nlordell** [comment]
> Looking at this I wonder if you need everything from the Orders struct or only a subset like sell and buy token. In that case I'd like to only return that subset and not the full order.

Maybe just the `OrderCreation` would be enough for now?

**Comment by alfetopito** [comment]
Agree with Nick.
Only what's in the order table should suffice.

Looking at the current UI https://pr611--gpui.review.gnosisdev.com/storybook/?path=/story/trade-tradestable--default
![screenshot_2021-09-09_14-58-37](https://user-images.githubusercontent.com/43217/132768042-2dbef65c-a2cc-4c7a-a659-d4354506932b.png)


and comparing with what's currently returned in the trade object

```
  {
    "blockNumber": 0,
    "logIndex": 0,
    "orderUid": "string",
    "owner": "0x6810e776880c02933d47db1b9fc05908e5386b96",
    "sellToken": "0x6810e776880c02933d47db1b9fc05908e5386b96",
    "buyToken": "0x6810e776880c02933d47db1b9fc05908e5386b96",
    "sellAmount": "1234567890",
    "sellAmountBeforeFees": "1234567890",
    "buyAmount": "1234567890",
    "transactionHash": "0xd51f28edffcaaa76be4a22f6375ad289272c037f3cc072345676e88d92ced8b5"
  }
```

We'll need the original buy amount and sell amount to calculate limit price and surplus. And kind as well.
That would be the bare minimum.

But since it's available already, I say it doesn't hurt to load the whole order row. I'd hate to bother you again soon because we now decided to show executed fee % in the table or something like that.

**Comment by vkgnosis** [comment]
Ran into a problem with the trades route. There is no easily indexable way to get all trades belonging to a user because in the trades table we only have the order uid. Then we need to have the order with that id in the database too to get the owner.
Now the naive way to get a user's trades involves scanning the whole trades table. We can do this but an index would be better. The index is complicated because it has to connect the order uid from the trade to the orders table.
For example there could be a new table that associates a trade primary key (blog number, log index) with the owner so that we can have an index on owner. This table would need to be updated when new orders get added and when new trades get added.
Instead of a new table we could also put the owner directly into the trade table. Either way we would need some kind of update task to backfill this information and probably run periodically.
Alternatively we might be able to accomplish what we want with a postgres view. I am still investigating how they work and if they would fit in this case.

**Comment by alfetopito** [comment]
It sounds to me the simplest way would be to de-normalize and add the `owner` column to the `Trades` table, plus an index for that.
For existing trades there can be a backfill script doing the expensive full scan - which is ok since should be needed only once.
For new trades I assume the owner info is available on insertion time, right?

I'm not familiar with Postgres views or triggers to comment on that option.

**Comment by fleupold** [comment]
Are we running into performance issues for listing all trades that belong to a trader already? If this is not a super time critical query maybe we can defer adding extra columns until it becomes an issue and use a normal full table scan until then?

**Comment by nlordell** [comment]
From what I understand, we already do this for owner orders (https://github.com/gnosis/gp-v2-services/pull/1081) using `OFFSET` and `LIMIT` as we did not think that we would run into performance issues and planned on doing the same for trades next.

**Comment by vkgnosis** [comment]
One difference is that on we have an index for the owner. So we only need to scan proportionally to the offset which is usually 0 because the frontend will show new trades first.
For trades the naive implementation always has to scan a good amount because there ti has to collect enough trades by that user to fill the page. Or for a user with no trades it will scan the whole table to find this out every time. This is still probably not a problem at the moment so to get the endpoint working we can implement it (will do when I have time again).

**Comment by anxolin** [comment]
If trades has a OrderUid field, which is a PK to the order, wouldn't be enough to do sth like:

```
SELECT trade.* FROM trades t JOIN orders o ON o.orderUid =  t.orderUid WHERE o.owner = ${owner}
```

Should be efficient enough and no replication, right? Not sure if im missing something

**Comment by vkgnosis** [comment]
We want the N newest trades of a user. Imagine a user that has not trades (or not enough trades to fill a page). We would have to scan through the whole trades table (trades of all users) to figure this out. For orders this is fixed by the index on owner. But for trades we cannot create such an index because there is no owner column in the trades table.
